### ISSUE TITLE
Function or not function is the question !

### ISSUE THREAD

**Issue by jmarcellopereira** [JuliaPy/SymPy.jl#100]
I'm with a doubt: 
A function in the reduced form is:
```
f(x) = x +1 # example 1 (generic function)
f(1)
2
```

Using sympy, I do :
```
using SymPy
@syms x
g = x + 1 # example 2
g(1)
2
```
My question is: can I say that the expression from example 2 is a function (according to the definition)? If not defined as function, what is the best definition of example 2?

**Comment by jverzani** [comment]
Well, I would say `g` is an expression and we are "plugging in" a value for x, were it a class. But that borrows from my student's vocabulary. Maybe better to say `g` is a "callable" expression, and you are calling it through function notation. How is that?

**Comment by jmarcellopereira** [comment]
Good explanation. I was left with this doubt because the form of attribution is similar to a function in reduced form.
