### ISSUE TITLE
range for Sym integers

### ISSUE THREAD

**Issue by mzaffalon** [JuliaPy/SymPy.jl#101]
I would like to be able to define a range with a `SymPy` integer, but there is no definition for SymPy ranges.

```
julia> Sym(1):Sym(3)
ERROR: PyError (:PyObject_Call) <class 'sympy.polys.polyerrors.ComputationFailed'>
...

julia> m = Sym(3);
julia> 1:m
ERROR: MethodError: no method matching colon(::Int64, ::SymPy.Sym)
```

I also seem not to be able to convert a SymPy integer to a Julia integer:
```
julia> Int64(Sym(3))
ERROR: PyError (PyInt_AsSsize_t) <class 'TypeError'>
TypeError('an integer is required',)
```
whereas the conversion to `Float64` works.

**Comment by jverzani** [comment]
I should add those conversions. For now, you can use `N`:

`N(Sym(1)):N(Sym(2))`

If this is a common pattern for you, let me know and we can look into adding a method to make it easier. It would be automatic, but SymPy values inherit from `Number`, not `Real`.

**Comment by mzaffalon** [comment]
The longer form is fine with me.
