### ISSUE TITLE
Expression manipulation using func, args

### ISSUE THREAD

**Issue by jagot** [JuliaPy/SymPy.jl#103]
I am trying to implement custom expression manipulation by walking the
expression tree and rewriting the subexpression I like. However, I have hit
two snags:

1. How do I identify the exponential function? Right now I do

    ```julia
    f,a = func(expr),args(expr)
    if srepr(f) == "exp" # Ugly?
      # Do something
    end
    ```

2. After rewriting the expression to my heart's content, how do I re-add it to the tree? According to http://docs.sympy.org/dev/tutorial/manipulation.html#args, it should be as simple as

      ```julia
      @syms x
      expr = x^2
      f,a = func(expr),args(expr)
      f(a...)
      ```

    but that gives me the error

    ```julia
    LoadError: PyError (:PyObject_GetIter) <class 'TypeError'>
    TypeError("'property' object is not iterable",)
    
    while loading In[229], in expression starting on line 1
    
     in pyerr_check at /Users/oo/.julia/v0.5/PyCall/src/exception.jl:56 [inlined]
     in pyerr_check at /Users/oo/.julia/v0.5/PyCall/src/exception.jl:61 [inlined]
     in macro expansion at /Users/oo/.julia/v0.5/PyCall/src/exception.jl:81 [inlined]
     in start(::PyCall.PyObject) at /Users/oo/.julia/v0.5/PyCall/src/conversions.jl:819
     in collect(::Type{Any}, ::PyCall.PyObject) at /Users/oo/.julia/v0.5/PyCall/src/conversions.jl:843
     in collect(::PyCall.PyObject) at /Users/oo/.julia/v0.5/PyCall/src/conversions.jl:848
     in (::SymPy.Sym)(::SymPy.Sym, ::SymPy.Sym, ::Vararg{SymPy.Sym,N}) at /Users/oo/.julia/v0.5/SymPy/src/call.jl:22
     ```
    
    EDIT: For reference, here is the expected result, using Python:
    <img width="344" alt="screen shot 2016-12-30 at 15 46 35" src="https://cloud.githubusercontent.com/assets/117947/21566857/6241722c-cea7-11e6-952c-bfa12d53dfcb.png">

**Comment by jverzani** [comment]
Yes, this is something that isn't fitting into the `call` method for SymPy objects. Here is a workaround, though it would be best to handle this in the `call` method:

```
ex = x^2
f = func(ex)
as = args(ex)
convert(Function, f.x)(as...)
```

Basically, the `call` method tries to handle any `free_symbols` which is where the error lies, but that isn't the proper approach for this type of SymPy object.

**Comment by jverzani** [comment]
With this commit, you should have `ex == func(ex)(args(ex)...)` holding. Let me know if this doesn't work for you.

**Comment by jagot** [comment]
Yes and no. If `ex = x^2`, the above works as expected:

```julia
using SymPy

@syms x
ex = x^2

ex == func(ex)(args(ex)...)
```

give the output

```
true
```

However, the base case I will encounter when walking the expression tree, results in an infinite recursion:

```julia
using SymPy

@syms x
ex = x

ex == func(ex)(args(ex)...)
```

gives the following output:

```
julia> include("/private/tmp/test.jl")

WARNING: Calling `subs` with keyword arguments will be deprecated. From v0.4 onward, the use of pairs, as in
`subs(ex, var1=>val1, var2=>val2)` is suggested.
WARNING: Calling `subs` with keyword arguments will be deprecated. From v0.4 onward, the use of pairs, as in
`subs(ex, var1=>val1, var2=>val2)` is suggested.
WARNING: Calling `subs` with keyword arguments will be deprecated. From v0.4 onward, the use of pairs, as in
`subs(ex, var1=>val1, var2=>val2)` is suggested.
WARNING: Calling `subs` with keyword arguments will be deprecated. From v0.4 onward, the use of pairs, as in
`subs(ex, var1=>val1, var2=>val2)` is suggested.

.
.
.
```

In my specific use-case, I can by-pass this by testing if `args(ex)==tuple()` and then return `ex`, instead of `func(ex)(args(ex)...)`, but that would not be possible if it was `func(ex)` I wanted to transform.

**Comment by jverzani** [comment]
Thanks, back to the drawing board...

**Comment by jverzani** [comment]
Does this commit 0dd3254 help?

**Comment by jagot** [comment]
Alas, no. Still same infinite error message.
My Julia/Python 3/SymPy versions:

```               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.0 (2016-09-19 18:14 UTC)
 _/ |\__'_|_|_|\__'_|  |  
|__/                   |  x86_64-apple-darwin16.0.0
```

```
❯ python3 --version
Python 3.6.0
```

```
❯ pip3 show sympy
Name: sympy
Version: 1.0
Summary: Computer algebra system (CAS) in Python
Home-page: http://sympy.org
Author: SymPy development team
Author-email: sympy@googlegroups.com
License: BSD
Location: /usr/local/lib/python3.6/site-packages
Requires: mpmath
```

What more information can I provide to aid you in the search?

**Comment by jverzani** [comment]
This is actually trickier than I thought. I'll check in some changes that remove the error messages, but it still leaves with the problem of recover `x` from `func(x)` as in this example `args(x)` is contentless. I don't know how to do that. You might have to check for objects of class `Symbol` before trying to stitch things together (`SymPy.classname(x) == "Symbol"` will work for that).

**Comment by jverzani** [comment]
Even better, in the SymPy docs I find:

> Every well-formed SymPy expression must either have empty args or satisfy expr == expr.func(*expr.args).

So, you should check the `args(x)` value as a base case when traversing, not the `func(x)` value. (Which would be a hassle, as the there are other leaf nodes besides `Symbol`.
