### ISSUE TITLE
implicit substitution in expression

### ISSUE THREAD

**Issue by mzaffalon** [JuliaPy/SymPy.jl#127]
Numerical values are substituted into an expression in the opposite order in which they are defined
```
x, y, z = symbols("x, y, z")
(z*y^2)(2, 1, 0) # --> 2
```
In the above expression, `z` is assigned the value 2, `y` the value 1 and `x` the value 0.
Is this intentional? It does not seem to be documented.

EDIT: it looks like `lambdify` is implicitly called on the expression.

**Comment by jverzani** [comment]
I thought I had a comment that in the absence of names, the order of substitution in the call is given by `free_symbols`. But this is missing, must be in the tutorial. It needs to be added. I guess to `subs`. However, this should probably throw an error, as there are only two free symbols in the expression.
