### ISSUE TITLE
Removal of method jacobian(Array{SymPy.Sym,1},Any)

### ISSUE THREAD

**Issue by angusmoore** [JuliaPy/SymPy.jl#129]
In SymPy v0.4.0 this works:
```
@vars x y z
foo = [x y z]
jacobian(foo,[x])
```
This gives a method error in SymPy 0.5.0, requiring a two-dimensional first argument.

Was this an intended change? The fix is obvious and simple, so if it was intended, it's not hard for me to fix my code. Just wanted to check/ask what the rationale was?

**Comment by mzaffalon** [comment]
It was probably the recent overhaul #122 that @jverzani made. The easy fix is (I guess)
```
SymPy.jacobian(A::Array{Sym}, B::Array{Sym}) = call_matrix_meth(A, :jacobian, B)
```
#128 should fix this.

**Comment by jverzani** [comment]
Thanks. No, not intentional, just got dropped in the overhaul for matrices. Thanks for catching and fixing you two.

**Comment by angusmoore** [comment]
Great, thanks guys, appreciate the work!
