### ISSUE TITLE
Functions like `is_real` not working?

### ISSUE THREAD

**Issue by Marlin-Na** [JuliaPy/SymPy.jl#139]
I did not get expected result for the following code:

```julia
using SymPy

@syms a real=true
# (a,)

is_real(a)
# (::__XXxxXX__) (generic function with 1 method)
```

I would expect `is_real` to return `true`, but it didn't for my case.

```julia
Pkg.status("SymPy")
# - SymPy                         0.4.0
```

**Comment by mzaffalon** [comment]
Can you update SymPy to 0.5.0 (`Pkg.update("SymPy")`) where `is_real` seems to be working fine? If not, it may take a bit to figure out what the problem is: @jverzani made some extensive changes between 0.4.0 and 0.5.0.

**Comment by jverzani** [comment]
Yes, and that bug was caught then. Report back if there are issues after upgrading.

**Comment by Marlin-Na** [comment]
Thanks for the explanation !
