### ISSUE TITLE
S = SymFunction("S") returns error "type SymFunction has no field x"

### ISSUE THREAD

**Issue by sylvaticus** [JuliaPy/SymPy.jl#140]
Complete stack:

> type SymFunction has no field x
> 
>  in limitstringmime(::MIME{Symbol("text/plain")}, ::SymPy.SymFunction) at /home/lobianco/.julia/v0.5/IJulia/src/execute_request.jl:31
>  in display_dict(::SymPy.SymFunction) at /home/lobianco/.julia/v0.5/IJulia/src/execute_request.jl:46
>  in execute_request(::ZMQ.Socket, ::IJulia.Msg) at /home/lobianco/.julia/v0.5/IJulia/src/execute_request.jl:200
>  in eventloop(::ZMQ.Socket) at /home/lobianco/.julia/v0.5/IJulia/src/eventloop.jl:8
>  in (::IJulia.##9#15)() at ./task.jl:360

`S = symbols("S", cls=symfunction)` works but rise a warning

> WARNING: Base.writemime is deprecated.
>   likely near /home/lobianco/.julia/v0.5/IJulia/src/kernel.jl:31
> in show at /home/lobianco/.julia/v0.5/PyCall/src/PyCall.jl 

Python 2.7.12, SymPy 1.0, Julia 0.5, SymPy.jl 0.4.0, PyCall 1.7.2, Ubuntu

**Comment by mzaffalon** [comment]
Can you update SymPy.jl to 0.5.0 (`Pkg.update("SymPy")` should do) and check if this solves the problem?

**Comment by jverzani** [comment]
Yes, `SymFunction` was changed. Defining them via the argument `cls=symfunction` was also deprecated for a technical reason. For now, `F = SymFunction("F")` or `@symfuns F G H` should be used. Reopen if after updating the SymPy package you still have issues.
