### ISSUE TITLE
`Subs` numeric value to variable?

### ISSUE THREAD

**Issue by Marlin-Na** [JuliaPy/SymPy.jl#142]
In python, it is possible to substitute a number in an expression to a variable:

```python
from sympy import *
x = symbols("x")
z = x + 1
z.subs(1,x)
# 2*x
```

Is it possible to do it in julia, as the `subs` function seems not to work as expected?

```julia
using SymPy
@syms x
# (x,)
z = x + 1
# x + 1
z |> subs(1 => x)
(::#110) (generic function with 1 method)
```

**Comment by jverzani** [comment]
You can get this behaviour via `sub(z, Sym(1) => x)`. Maybe it would make sense to convert the expression of the left hand side of the pair to a symbolic expression, in which case your style would work.

**Comment by Marlin-Na** [comment]
Thanks for both answers and this remarkable package!
