### ISSUE TITLE
Re-enable appveyor

### ISSUE THREAD

**Issue by tkelman** [JuliaPy/SymPy.jl#145]
The webhook has been failing ever since the repository was moved to this organization, ref https://ci.appveyor.com/project/jverzani/sympy-jl

**Comment by jverzani** [comment]
This is something done by the JuliaPy organizers?

**Comment by tkelman** [comment]
It's running on your account at appveyor, so I think you need to do it.

**Comment by jverzani** [comment]
I pointed the configuration to `JuliaPy/SymPy.jl` and restarted the build to see that it pulled in master (it did), but I'm not sure changes to `JuliaPy/SymPy.jl` will trigger a build or will only changes to `jverzani/SymPy.jl`. Hope it works, as I'm out of my depth with knowing how this all fits together.
