### ISSUE TITLE
Method to check if expression contains a symbol

### ISSUE THREAD

**Issue by djsegal** [JuliaPy/SymPy.jl#147]
for example, if

+ `eq_1 = a * Sym("T") + b * Sym("T")^2` 
+ `eq_2 = a + b`

then

```
contains(eq_1, Sym("T"))  # equals true
contains(eq_2, Sym("T"))  # equals false
```

**Comment by jverzani** [comment]
You have `free_symbols` to list all symbols, so this would work:

```
Base.contains(haystack::Sym, needle::Sym) = needle ∈ free_symbols(haystack)
```

However, SymPy has "has" for this, and we mirror that:

```
has(ex, variable)
```
