### ISSUE TITLE
Correct canceling for non-integer powers

### ISSUE THREAD

**Issue by djsegal** [JuliaPy/SymPy.jl#148]
for example, 

+ `105*R_0^2.07*alpha^1.38*beta^0.69*(R_0^3*alpha^2*beta)^(-0.69)`

should turn into just

+ `105`

------------

so far, `simplify`, `expand`, and `N` do nothing (`N` here obviously enters an infinite loop)

**edit:** i realize this is a have your cake situation, but maybe it might be possible to do it by using fractional values?

**Comment by jverzani** [comment]
SymPy has some assumptions about powers that are stronger if you put assumptions on the variables. Try it with:

```
@vars R_0 alpha beta positive=true
```

And
```
@vars R_0 alpha beta real=true
```

And you will see the difference.

**Comment by djsegal** [comment]
@jverzani

after forcing everything to be positive, I'm now getting something like this:

`
105 * B_0^(3/20) * I_M^(93/100) * R_0^(1/10) * n_bar^(97/100) * sigma_v_hat ^ (69/100) / ( B_0^(3/20) * I_M^(93/100) * R_0^(1/10) * n_bar^(97/100) * sigma_v_hat^(69/100) )
`

------

or in a more cleaned up form:

```
a = 105
  *B_0^(3/20)
  *I_M^(93/100)
  *R_0^(1/10)
  *n_bar^(97/100)
  *sigma_v_hat^(69/100)

b = (B_0^(3/20)
  *I_M^(93/100)
  *R_0^(1/10)
  *n_bar^(97/100)
  *sigma_v_hat^(69/100))

a /= b
```

there should be some way to make that expression evaluate to `105` (`N` stalls at the moment)

**Comment by djsegal** [comment]
nvm. closed (had to change `Sym` to `symbols(..., positive=true)` in the tests too)

**Comment by jverzani** [comment]
Okay, thanks for following up, I couldn't replicate it.
