### ISSUE TITLE
Misplaced contents in a result

### ISSUE THREAD

**Issue by anymate98** [JuliaPy/SymPy.jl#162]
![integrate(sqrt(1-x^2),x)](https://cloud.githubusercontent.com/assets/26593166/26711202/b75f1c80-4799-11e7-9715-64543cb5201f.png)

While using Sympy, I got the result above. Looks like 'asin(x)' and '2' should move to the right.
Is there any way I could fix this problem?
I'm using julia 0.5.2, win10
It works fine in my linux VM..

**Comment by mzaffalon** [comment]
What terminal do you use? [ConEmu](https://conemu.github.io/) displays the results correctly on Windows 7, although the continuous fraction line is replaced by a dashed line.

An alternative is to use SymPy in IJulia.

**Comment by anymate98** [comment]
I guess cmd is a problem. It works perfect with git bash. Thanks.
