### ISSUE TITLE
Difficulty accessing sympy version of elliptic functions

### ISSUE THREAD

**Issue by djsegal** [JuliaPy/SymPy.jl#164]
I have some symbols that need to be part of an elliptic integral call.

// see the [sympy docs](http://docs.sympy.org/dev/modules/functions/special.html#module-sympy.functions.special.elliptic_integrals) on elliptic calls

However, I can't access the sympy version at all.

I've tried `mpmath.ellipk(cur_val)`, for example, but this only works with numbers

**Comment by djsegal** [comment]
**update**

got it to work with:

+ `sympy_meth(:elliptic_k, cur_val)`

**Comment by mzaffalon** [comment]
Would you consider making a PR to expose `elliptic_k`?

**Comment by jverzani** [comment]
Yes, great idea. I think the `physics.jl` file can give an idea of how to wrap up all the features from the elliptical integrals part. Or would this be better in `specialfuns.jl` @mzaffalon ?

**Comment by mzaffalon** [comment]
We could do the same as sympy.py and wrap them (`elliptic_e`, `elliptic_f`, `elliptic_pi`) under `specialfuns.jl`.

**Comment by jverzani** [comment]
Sounds like that would be best. Should I do it, you or @djsegal ?

**Comment by mzaffalon** [comment]
@djsegal Would you like to have a go at it?
