### ISSUE TITLE
Way to feasibly integrate an interpolated function

### ISSUE THREAD

**Issue by djsegal** [JuliaPy/SymPy.jl#181]
I don't think BSplines got brought over from the python version.

Is there a way to accomplish this in `O(seconds)` time?

**Comment by djsegal** [comment]
Some test data:

```
table_T = [
     0.00
     1.00
     1.50
     2.00
     2.50
     3.00
     3.50
     4.00
     4.50
     5.00
     5.50
     6.00
     6.50
     7.00
     7.50
     8.00
     8.50
     9.00
     9.50
    10.00
    15.00
    20.00
    25.00
]

table_sigma_v = [
  0.0000e-00
  5.4835e-21
  5.8917e-20
  2.6276e-20
  7.6096e-19
  1.7128e-18
  3.2740e-18
  5.5843e-18
  8.7602e-18
  1.2891e-17
  1.8039e-17
  2.4237e-17
  3.1494e-17
  3.9797e-17
  4.9111e-17
  5.9391e-17
  7.0576e-17
  8.2598e-17
  9.5385e-17
  1.0886e-16
  2.6542e-16
  4.2434e-16
  5.5940e-16
]
```

--------------

```
using SymPy

@syms T_0

function foo(rho)
  SymPy.interpolate(table_T, table_sigma_v, T_0 / ( 1 - rho ) ^ 2 )  * rho ^ 3 + rho
end

@syms rho_0

function bar()
  b = 3
  c = 1.3

  SymPy.integrate(foo(rho_0), (rho_0, 0.0, 1.0) * 1e2 * b / c
end
```

**Comment by jverzani** [comment]
This may be an issue with `integrate`. I tried it with `1/(1-rho)^2` replaced by `* (1-rho)^2` and the setup returns an answer.

**Comment by jverzani** [comment]
I think the issue the integrability of `1/(1-rho)^(2k)` near 1. The interpolating polynomial is comprised of these terms. One thing you can try is to convert the interpolated polynomial (in an x variable) into a `Poly` object, pull out its coefficients, transform each, integrate term by term and add. This will show the problem.

**Comment by jverzani** [comment]
i'm not sure this requires a change. Please reopen if it does.
