### ISSUE TITLE
gamma() and binomial() with symbolic arguments not supported

### ISSUE THREAD

**Issue by ko56** [JuliaPy/SymPy.jl#184]
In Julia 0.6.0, I get the following errors

```
> using SymPy
> @syms x m n

> gamma(x)
MethodError: no method matching gamma(::SymPy.Sym)
Closest candidates are:
  gamma(::BigFloat) at mpfr.jl:637
  gamma(::Float32) at special/gamma.jl:4
  gamma(::Float64) at special/gamma.jl:3
  ...

Stacktrace:
 [1] include_string at ./loading.jl:515

> binomial(n,m)
MethodError: no method matching binomial(::SymPy.Sym, ::SymPy.Sym)

Stacktrace:
 [1] include_string at ./loading.jl:515
```

**Comment by mzaffalon** [comment]
It works if you call `gamma` in the following way:
```
julia> using SymPy.SpecialFuncs
julia> SymPy.SpecialFuncs.gamma(x)
Γ(x)
```
Should SymPy's `gamma` overload `Base.gamma`?

**Comment by jverzani** [comment]
I think so, but probably this should be done in the SpecialFuncs module.

**Comment by ko56** [comment]
I imagine this overloading issue arises in lots of places between Julia and SymPy.

**Comment by jverzani** [comment]
Yes, typically we just overload the base function for objects of Sym type.

**Comment by jverzani** [comment]
I added a branch `v0.6-7` that has this fix. Will merge into master when 0.7 rolls around.
