### ISSUE TITLE
Reduce complexity of variables with composite variables

### ISSUE THREAD

**Issue by djsegal** [JuliaPy/SymPy.jl#186]
lets say you had:

```
@syms a b c f
d = a + f * b / c
e = b/c
```

------

Is there a way to make it:

```
d = a + f * e
```

**Comment by mzaffalon** [comment]
Maybe `xreplace`? http://docs.sympy.org/latest/modules/core.html?highlight=replace#sympy.core.basic.Basic.xreplace

**Comment by djsegal** [comment]
I lied. I have:

```
@syms a b c f
d = a + f * b / c
e = b/c
```

and I want it as:

```
d = a + f * e
```

I think this requires `replace` with wildcard chars, but this is glitchy 

// sympy.jl's source code says it doesn't work too

What should I do? Is there something that needs fixing?

**Comment by mzaffalon** [comment]
Does `sympy.py` do what you need?

**Comment by djsegal** [comment]
Guess you're right. SymPy.py does the same weird behavior:

```
> a = Wild("a")
> @syms b c d e f g

> phrase = c * d / e
> eq = b * c * d / e + f

b⋅c⋅d
───── + f
  e
```

leads to:

```
> replace(eq, a*phrase, a*g)

     -e⋅g
     ─────
      c⋅d
b⋅e⋅e     ⋅g + f
```

and

```
> xreplace(eq, phrase => g)

b⋅c⋅d
───── + f
  e
```

-----

This seems to be out of scope, just thought I'd ask

**Comment by asmeurer** [comment]
I don't know the Julia version, but in Python SymPy `subs` does this:

```
>>> eq.subs(phrase, g)
b*g + f
```

xreplace only replaces exact expressions, and `c * d / e` does not appear exactly in the expression tree of `eq`. `replace` with a Wild is doing something weird. It should probably be considered a SymPy bug.

**Comment by djsegal** [comment]
duh. lol 😞

**Comment by asmeurer** [comment]
I do think the replace thing is a bug. I opened https://github.com/sympy/sympy/issues/13323 for it.
