### ISSUE TITLE
Warnings generated for sin(x), cos(x) in Julia 0.6

### ISSUE THREAD

**Issue by mopg** [JuliaPy/SymPy.jl#188]
When you have a symbolic function with sin(x) or cos(x) in it, and want to call this function with a vector of floats (after converting it using `lambdify`), warnings are generated. This is because the function then uses `sin(x)`, and not `sin.(x)`.

It still works, would just be nice if it would get fixed such that the warnings are no longer generated.

**Comment by mzaffalon** [comment]
What prevents you from calling the dotted version of the symbolic function?
```
julia> using SymPy; x = symbols("x"); g = sin(x);
julia> lambdify(g).(randn(5))
# Compat.UTF8String warnings here...
5-element Array{Float64,1}:
  0.685097
  0.234293
 -0.0384181
 -0.999862
  0.242143
```

**Comment by mopg** [comment]
I had no idea you could do that. Apologies and thanks for the help!
