### ISSUE TITLE
Overriding `Dict` show method - type piracy?

### ISSUE THREAD

**Issue by karenl7** [JuliaPy/SymPy.jl#194]
I just ran into a tricky SymPy/IJulia issue where I was constructing a large dictionary as the last line in a cell and got this ominous output:
```
In[50]: <code constructing large dictionary>
Out[50]: [Math Processing Error]
```
After a bit of digging, it seems that the culprit is this [`show` method](https://github.com/JuliaPy/SymPy.jl/blob/master/src/display.jl#L64) from SymPy.jl which overrides the default print behavior of all `Dict`s. This was somewhat tricky to find as I had loaded SymPy long before for purposes unrelated to the code I was running in that cell.

It seems like this sort of `show` method is ["type piracy"](https://docs.julialang.org/en/latest/manual/style-guide/#Don't-overload-methods-of-base-container-types-1) according to the Julia style guide and it feels like this may confuse other people in similarly unexpected ways. Can that `show` method be removed or otherwise have its scope more limited (maybe `S<:Sym` in the method definition?).

**Comment by jverzani** [comment]
Bad form on our part. I'll fix this as suggested by narrowing to Sym object. Sorry about this.
