### ISSUE TITLE
Extract Julia code from SymPy expression?

### ISSUE THREAD

**Issue by dpsanders** [JuliaPy/SymPy.jl#198]
Is there a way of extracting the Julia code from a SymPy expression, i.e. what `lambdify` does but returning the Julia source code for the body of the function, instead of the anonymous function itself?

**Comment by mzaffalon** [comment]
Is what you want the `fn` defined at https://github.com/JuliaPy/SymPy.jl/blob/master/src/lambdify.jl#L150? The following line returns the anonymous function?

**Comment by dpsanders** [comment]
Thanks it looks like `sympy_meth(:julia_code, s)` is actually what I was looking for.

**Comment by asmeurer** [comment]
SymPy also has a built in Julia code generator https://github.com/sympy/sympy/blob/master/sympy/printing/julia.py

**Comment by ccmejia** [comment]
> SymPy also has a built in Julia code generator https://github.com/sympy/sympy/blob/master/sympy/printing/julia.py

I’ve been trying whit  julia_code generator but it seems that I must should do something before: 
UndefVarError: julia_code not defined
:(

**Comment by jverzani** [comment]
This is in the  `lambdify` code defn:


```
body = Meta.parse(sympy.julia_code(ex))
```

We don't actually use it unless asked, as there had been issues with a few things.

If that isn't what you are lookiing for, please re-open.
