### ISSUE TITLE
Defining symbolic variables

### ISSUE THREAD

**Issue by moesphere** [JuliaPy/SymPy.jl#201]
With SymPy 0.5.4 and PyCall 1.15.0 I get following error when declaring a symbolic variable using symbols:

`@syms x`
`ArgumentError: ref of NULL PyObject`

**Comment by mzaffalon** [comment]
How was this solved?

**Comment by moesphere** [comment]
I did not really solve it. I previously installed JuliaPro on my Windows laptop, where the mentioned error occured. I removed it and installed julia from the GitHub repository and added the needed packages using the package manager. The error was then gone.

**Comment by mzaffalon** [comment]
On a Windows platform, you can download the binaries from Julia's website without the need for compilation.

**Comment by moesphere** [comment]
That was also what I did. I downloaded the binaries from the julia web page, not from github. My bad!
