### ISSUE TITLE
Greek symbols

### ISSUE THREAD

**Issue by DeathByDenim** [JuliaPy/SymPy.jl#208]
As far as I understand the documentation, all of these are equivalent:

    x = symbols("x")		       # or   @vars x, Sym("x"), or  Sym(:x)

And that indeed works for "x". However, for Greek letters there are issues. For example, ξ. I cannot do

    symbols("ξ")
    @vars ξ
    Sym("ξ")
    Sym(:ξ)`

because Unicode characters do not seem to be supported. The error is:

    PyError (ccall(@pysym(:PyObject_Call), PyPtr, (PyPtr, PyPtr, PyPtr), o, arg, kw)) <type 'exceptions.UnicodeEncodeError'>
    UnicodeEncodeError('ascii', u'\u03be', 0, 1, 'ordinal not in range(128)')

If I use "xi" instead it works in most cases, but the output is not always the same:

    In[1] : symbols("xi")
    Out[1]: ξ
    In[2] : @vars xi
    Out[2]: (xi,)
    In[3] : Sym("xi")
    Out[3]: ξ
    In[4] : Sym(:xi)
    Out[4]: ξ

Additional problems occur when the greek letter is also a predefined function in Julia, such as ζ.

    In[1] : symbols("zeta")
    Out[1]: ζ
    In[2] : @vars zets
    Out[2]: (zeta,)
    In[3] : Sym("zeta")
    Out[3]: PyObject zeta
    In[4] : Sym(:zeta)
    Out[4]: PyObject zeta

**Comment by mzaffalon** [comment]
Is it possible that you have Python 2 installed instead of Python 3?

Even on Linux, I use
```
ENV["PYTHON"] = ""
ENV["CONDA_JL_VERSION"] = 3
```
in my `.juliarc.jl` startup file and let Conda.jl manage the Python installation.

**Comment by DeathByDenim** [comment]
Ah yes, it appears to be using 2.7.14 according to `Conda.list()`. I didn't realize that Python 3 was required for Unicode support. Switching to 3 did fix a bunch of things for the Unicode stuff. Though not all:

    In [1]: symbols("ξ")
    Out[1]: ξ
    In [2]: @vars ξ
    Out[2]: (ξ,)
    In [3]: Sym("ξ")
    PyError (ccall(@pysym(:PyObject_Call), PyPtr, (PyPtr, PyPtr, PyPtr), o, arg, C_NULL)) <class 'NameError'>
    NameError("name 'ξ' is not defined",)
    In [4]: Sym(:ξ)
    PyError (ccall(@pysym(:PyObject_Call), PyPtr, (PyPtr, PyPtr, PyPtr), o, arg, C_NULL)) <class 'NameError'>
    NameError("name 'ξ' is not defined",)

The other things were I used "xi" and "zeta" still have the same behaviour though. That is, inconsistencies between the different ways of creating a symbol.

**Comment by mzaffalon** [comment]
`Sym("\mu")` works too, but not `Sym("μ")`.

**Comment by jverzani** [comment]
I'm not sure how to fix this and it seems like a python issue, not a `SymPy.jl` one. Please re-open if there is something actionable.
