### ISSUE TITLE
accessing sympy's help() function

### ISSUE THREAD

**Issue by ko56** [JuliaPy/SymPy.jl#211]
Is it possible to use SymPy's help() function?  With Julia 0.6.2 I get

`julia> help(sin)`
`ERROR: UndefVarError: help not defined`

**Comment by mzaffalon** [comment]
For help, you should type a question mark on your command line and the prompt will change from `julia>` to `help?>`. Then type the function you need help for. Note that this has nothing to do with SymPy but is basic Julia functionality.
```
julia> using SymPy
INFO: Recompiling stale cache file /home/michele/.julia/lib/v0.6/SymPy.ji for module SymPy.

help?> sin
search: sin sinh sind sinc sinpi sine_transform singular_values asin using isinf asinh asind isinteger

  sin(x)

  Compute sine of x, where x is in radians.

  sin: a SymPy function. The SymPy documentation can be found through:
  http://docs.sympy.org/latest/search.html?q=sin
```

**Comment by ko56** [comment]
Yes, of course.  But I am talking about accessing SymPy's help, not Julia's.

**Comment by mzaffalon** [comment]
As far as I know, this has never been possible. If you look for `SymPy.jl` help, you are referred to `sympy.org` website, as Julia's help is telling you.

**Comment by ko56** [comment]
It is possible if you are using python and SymPy.  I wonder what it would take to make it usable from Julia.  I think it would very helpful :-) for Julia/Sympy.

**Comment by jverzani** [comment]
Thanks for the question. This is possible and I hadn't thought about it. What interface though?

```
sympy_help(ex::Sym) = PyCall.builtin[:help](func(ex))
```

Would work like `sympy_help(sin(x))`.

Whereas

```
sympy_help(ex::Symbol) = PyCall.builtin[:help](sympy[ex])
```

Would work like `sympy_help(:sin)`

The former requires an extra `(x)` and is definitely fussy (for functions of multiple arguments it will be different, ...), the latter requires some internal knowledge. Of course both are possible, but neither seems ideal.

Maybe just

```
sympy_help(ex) = PyCall.builtin[:help](sympy[Symbol(ex)])
```

is best, and would work when the names happen to match, as with `sympy_help(sin)`.

Any comments?

**Comment by jverzani** [comment]
See #213 for a possible implementation. Suggestions are welcome on the interface or the name.

**Comment by asmeurer** [comment]
`help` is just a Python function, not a SymPy function. All it does is show the docstring (`obj.__doc__`) in a pager (as well as some extra information, like the attributes and methods on the object).

**Comment by jverzani** [comment]
Ahh, thanks for this info. I redid this to use the method for `Base.Docs.doc` in PyCall. It doesn't use the pager now, but isn't misnamed anymore.
