### ISSUE TITLE
How to access values in Dict{SymPy.Sym, SymPy.Sym} by key?

### ISSUE THREAD

**Issue by junyuan-chen** [JuliaPy/SymPy.jl#215]
After using solve() to solve a system of equations, I get the solutions as shown in the picture below. However, I couldn't figure out how to access the values by key. I could only use map(N, values(sol)) to get the values now.  A much better way for my later manipulation on the solutions would require me to either 1) access values by key; or 2) convert the Dict{SymPy.Sym, SymPy.Sym} into Dict{String, Float64}. Is there already a solution for this? Thank you!

<img width="449" alt="screen shot 2018-04-25 at 3 46 55 pm" src="https://user-images.githubusercontent.com/37969042/39276956-4be80daa-48a0-11e8-997b-14b92e57f141.png">

**Comment by mzaffalon** [comment]
This is a question you should post in Discourse, not as an issue. Please close this issue, post the question on Discourse so that if solved, other users can benefit from it and post a _minimal_ working example of how you generate the code above.

**Comment by jverzani** [comment]
The second isn't possible. There there is no hashing difference between `symbols(:x)` and `symbols("x")`, there is between `symbols("x", real=true)` (something with assumptions). Hence we can't recover the key from a string or symbol in all cases, and less than that would be confusing (not just inconvenient). You should be able to access the Dict by a key though by passing in the original variable, say `vkk`.
