### ISSUE TITLE
floating point numbers not correctly wrapped

### ISSUE THREAD

**Issue by mzaffalon** [JuliaPy/SymPy.jl#217]
`(1 + Sym("0.0065")) - 1` should return `0.0065` and not the floating point number `0.00649999999999995`. The evaluation is fine under sympy.py.

Ref: https://discourse.julialang.org/t/solving-a-simple-equation-in-sympy-jl-fails/11146

**Comment by jverzani** [comment]
The current implementation calls `sympy[:sympify]`. What did you use with
sympy.jl?

**Comment by jverzani** [comment]
So far I have several options to use, none an improvement:

```
sympy[:Float]("0.0065", [prec])

sympy[:parsing]["sympy_parser"][:parse_expr]("0.0065")
sympy[:sympify]("0.0065")

object_meth(Sym(Rational(parse(BigFloat, "0.0065"))), :evalf)
```

If there is a means to parse as an exact number that would be great, but I
can't find the method.

**Comment by jverzani** [comment]
I see [this](http://www.sympygamma.com/input/?i=%281+%2B+sympify%28%220.0065%22%29%29+-+1)

I'm not sure what to do to avoid the round off.

**Comment by jverzani** [comment]
Sorry for the blast of thoughts, but this one might be a bit better, though not general so would have to expose some other way (maybe as `mpf`):

```
julia> (1 + SymPy.mpmath[:mpf]("0.0065")) - 1
6.500000000000000000000000000000000000000000000000000000000000000000000000003593e-03
```

**Comment by mzaffalon** [comment]
It looks like [this](http://www.sympygamma.com/input/?i=%281+%2B+symbols%28%220.0065%22%29%29+-+1) is OK: `(1 + symbols("0.0065")) - 1`.

**Comment by jverzani** [comment]
I wish that was right. It creates a "variable" 0.0065. I can't seem to do any numeric work with it. [here](http://www.sympygamma.com/input/?i=%28%281+%2B+symbols%28%220.0065%22%29%29+-+1%29+%2B+2)

**Comment by mzaffalon** [comment]
So the only way is to write it as a rational `Integer(65)/10000`?

**Comment by mzaffalon** [comment]
Personally, I would leave as is because SymPy.jl is a wrapper to sympy.py. If there is an issue, it should be solved upstream.

**Comment by mzaffalon** [comment]
Can this issue be closed?
