### ISSUE TITLE
lambdify apply to matrix (or array) or number

### ISSUE THREAD

**Issue by wuhuagumu** [JuliaPy/SymPy.jl#218]
In python+sympy environment, we can easily lambdify a matrix expression into a function or lambdify the expression to return a sympy expression:

    from sympy import *
    s = Matrix([[1, 0], [0, 1]])
    x, y = symbols('x y')
    
    fun = lambdify(x, x * s)
    print(fun(2))
    
    fun1 = lambdify(x,x + y)
    print(fun1(2))

In the above code, `fun` returns a numpy array, and `fun1` returns a sympy expression. 

However, I cannot use `lambdify` like these in `SymPy.jl`. Especially, in julia `lambdify(1,x)` or more specificaly `lambdify(PI,x)` are 
 illegal.  Any recommendations?

**Comment by jverzani** [comment]
The "lambdify" function doesn't really follow the calling pattern of SymPy's. For the second, it expects all symbols to be passed in to the function, not just "x" of "x" and "y". For the former, we could make a separate method for an expression which is a matrix. You can get pretty far with:
```
M = lambdify.(x*s)
[m(u) for u in M]
```
But this has issues with the value of 0 that need addressing.

Anyways, thanks for bringing this up, I'll see what can be done.

**Comment by mistguy** [comment]
I have a workaround here,

```julia
using SymPy

function mlambdify(expr, vars)
    f = lambdify.(expr, [vars,])
    return (args...) -> map.(f, args...)
end

@vars x y
f = mlambdify([x 0; 0 y], [x, y])

f(1.0, 2.0)
#2×2 Array{Real,2}:
# 1.0  0
# 0    2.0
```

**Comment by wuhuagumu** [comment]
Thanks for your answer. 

> But this has issues with the value of 0 that need addressing.

I noticed this can be solved by making 0 a SymPy object:

    lambdify(Sym(0),[x])

**Comment by jverzani** [comment]
Thanks for the feedback. See PR #219 to comment further. If there are no objections, I'll merge in a day or two.
