### ISSUE TITLE
Return type of eigvals(a::Matrix{Sym}) is Vector{Any}

### ISSUE THREAD

**Issue by olof3** [JuliaPy/SymPy.jl#222]
Shouldn't it be Vector{Sym}, or am I missing somthing?

With 
```julia
A = [Sym("a") 1; 0 1]
roots = eigvals(A)
```
`roots` gets type `Vector{Any}` and you cannot, for example, directly create a polynomial from `roots` using `Polynomials.poly`

**Comment by jverzani** [comment]
Interesting, this is the difference between:

```
[k for (k,v) in A[:eigenvals]()]
```

and the current

```
collect(keys(A[:eigenvals]()))
```

I'll make a PR.

Am curious what features of `Polynomials` you want to work with here that aren't in `SymPy`. Likely that means something needs to be exposed on the SymPy end.

**Comment by olof3** [comment]
Thanks. In the ControlSystems package we use ratios of Polynomials.Poly for one representation of rational LTI systems. It would be good if these rational functions could support symbolic entries without having to modify things to work with SymPy's representation of polynomials.

Along this line it would also be nice if it was possible to find the roots of Poly{SymPy,Sym} by falling back to some method in SymPy.

perhaps using something like this

```julia
@require SymPy begin
function Polynomials.roots(p::Polynomials.Poly{SymPy.Sym})
    x = SymPy.Sym("x")
    return SymPy.solve(p(x), x)
end
end
```

Do you have any thoughts on how to handle this in a nice way?

**Comment by jverzani** [comment]
Hmm, nothing pops to mind on how to make this nicer. Sorry.
