### ISSUE TITLE
Would be convenient with function complex(::Type{Sym}) = Sym

### ISSUE THREAD

**Issue by olof3** [JuliaPy/SymPy.jl#223]
I think it would be good to have a function 

```julia
complex(::Type{Sym}) = Sym
```

which would make it easier to treat Sym objects in the same way as other numbers.

**Comment by jverzani** [comment]
It seems like this is reasonable, but still has an issue for construction of Complex numbers as `!(SymPy.Sym  <: Real)`. Is there some other use case where this is helpful?

**Comment by olof3** [comment]
Sorry, I don't really get what you are referring to..

Anyway, some more info:

From the documentation of `complex(T::Type)`:

> Returns an appropriate type which can represent a value of type T as a complex number.
> Equivalent to `typeof(complex(zero(T)))`

maybe there should be a function `complex(x::Sym) = x` as well?

The use case where I was missing this function was in determining a type that can, e.g., represent the eigenvalues of a Matrix{T}.

**Comment by jverzani** [comment]
Yeah, the point I'm trying to make is that if we define `complex(::Type{Sym}) = Sym` (which is perfectly reasonable) we still have the issue that `Complex{Sym}` isn't suitable, as Sym is not <: Real. Anyways, I'm happy to do this, as I don't see where it hurts.  As for `complex(x::Sym) = x` that is a agood question. The current defn. is a bit lacking, though one could make the argument that defining it through `complex(r::Sym, i::Sym=Zero(Sym)) = N(r) + im*N(i)` is also reasonable.
