### ISSUE TITLE
Error when using lambdify on expression containing conjugate symbol

### ISSUE THREAD

**Issue by david-pl** [JuliaPy/SymPy.jl#242]
I am trying to convert some SymPy expressions to Julia code using `lambdify`, but I am running into problems when there is a complex conjugate. See the following example:
```julia
using SymPy
@syms x
expr = conjugate(x)
f = lambdify(expr)
f(1.0im)
```
This throws `ERROR: MethodError: no method matching conjugate(::Complex{Float64})`.

For now I am using the (very hacky) workaround simply defining the method `SymPy.conjugate(x::Number) = Base.conj(x)`.

I also noticed that `SymPy.sympy_meth(:julia_code, expr)` gives the correct expression (using `conj`), but it returns a string, which is not what I am looking for.

**Comment by jverzani** [comment]
Yes, this may have worked, but if I have it right, `conjugate` is no longer defined except for restricted number types. One fix would be to refactor the lambdify function to take  the body after either calling `:julia_code` or `walk_expression`, then the user could choose one or the other (as both have edge cases). I'll try and attend to that soon.
