### ISSUE TITLE
SymPy.jl breaks pdf export in Jupyter when displaying matrices

### ISSUE THREAD

**Issue by tbenst** [JuliaPy/SymPy.jl#248]
Try exporting https://gist.github.com/tbenst/559706b9e2aac87c233466647edc2ba3 to a pdf in Jupyter

**Comment by jverzani** [comment]
Are you getting `nbconvert failed: Inkscape svg to pdf conversion failed` (That's what I get in juliabox, but it isn't due to the matrix printing.)

**Comment by jverzani** [comment]
Okay, I think I tracked this down.
