### ISSUE TITLE
det and symbolic matrices

### ISSUE THREAD

**Issue by jverzani** [JuliaPy/SymPy.jl#256]
Not all work now (the default pivots in `lu` decomposition?)

```
@vars rho phi theta real=true
xs = [rho*cos(theta)*sin(phi), rho*sin(theta)*sin(phi), rho*cos(phi)]
J = Sym[diff(x, u) for x in xs, u in (rho, phi, theta)]
det(J) # raises error
sympy[:det](J) # computed
```

**Comment by AshtonSBradley** [comment]
`eigvecs` and `eigvals` are missing now too.

**Comment by jverzani** [comment]
There have been some changes. I think you need to call `using LinearAlgebra` before you can use `eigvecs` or `eigvals`. (If that doesn't help, please let me know.) This fixes `det` which has a different generic implementation than it used to.

**Comment by AshtonSBradley** [comment]
oh, awesome! thanks!
