### ISSUE TITLE
Problem with dsolve

### ISSUE THREAD

**Issue by Kelvyn88** [JuliaPy/SymPy.jl#264]
The next code used to work few days ago:

using SymPy

F = SymFunction("F")
x = Sym("x")

deq1 = 5F'(x) + 4F(x) - 2

sol = dsolve(deq1,x,(F,0,1))

but now I{m getting this error:

ERROR: PyError ($(Expr(:escape, :(ccall(#= C:\Users\kelvy\.julia\packages\PyCall\a5Jd3\src\pyfncall.jl:44 =# @pysym(:PyObject_Call), PyPtr, (PyPtr, PyPtr, PyPtr), o, pyargsptr, kw))))) <class 'ValueError'>
ValueError('dsolve() and classify_ode() only work with functions of one variable, not x',)
  File "C:\Users\kelvy\.julia\conda\3\lib\site-packages\sympy\solvers\ode.py", line 630, in dsolve
    x0=x0, n=n, **kwargs)
  File "C:\Users\kelvy\.julia\conda\3\lib\site-packages\sympy\solvers\deutils.py", line 205, in _desolve
    n=terms, x0=x0, prep=prep)
  File "C:\Users\kelvy\.julia\conda\3\lib\site-packages\sympy\solvers\ode.py", line 941, in classify_ode
    "work with functions of one variable, not %s" % func)

**Comment by jverzani** [comment]
Sorry, this is a bug. I changed this code and a few days ago, and didn't catch all the cases. Will fix soon. Thanks for reporting.

**Comment by jverzani** [comment]
Ahh yes, I rewrote this trying to hew more closely to the `sympy.dsolve` function, so now initial conditions use the `ics` keyword, as would be used in sympy with Python. So, replace your last line with:

```
sol = dsolve(deq1,x, ics=(F,0,1))
```
