### ISSUE TITLE
Finding the SymPy version

### ISSUE THREAD

**Issue by steinQF** [JuliaPy/SymPy.jl#267]
I'm looking for a way (not necessarily a convenience function, although that would be nice) to verify which SymPy version this package uses. According to https://stackoverflow.com/a/29825962/2127434, this would be achieved by the following python code:

```python
import sympy
sympy.__version__
```

What is the equivalent call using SymPy.jl?

**Comment by mzaffalon** [comment]
`SymPy.sympy.__version__` maybe?

**Comment by steinQF** [comment]
Wonderful, thank you!
