### ISSUE TITLE
Bug report: `nsolve` not defined for multiple variables

### ISSUE THREAD

**Issue by steinQF** [JuliaPy/SymPy.jl#268]
Steps to reproduce:

```
julia> using SymPy
julia> @vars z1 positive=true
(z1,)

julia> @vars z2z1 positive=true
(z2z1,)

julia> solve([z1^2-1, z1+z2z1-2], [z1,z2z1])
1-element Array{Tuple{Sym,Sym},1}:
 (1, 1)

julia> nsolve([z1^2-1, z1+z2z1-2], [z1,z2z1], [1,1])
ERROR: MethodError: no method matching nsolve(::Array{Sym,1}, ::Array{Sym,1}, ::Array{Int64,1})
Closest candidates are:
  nsolve(::SymPy.SymbolicObject, ::Any...; kwargs...) at /home/steinb/.julia/packages/SymPy/woEOA/src/importexport.jl:120
```

Expected result:
Successful execution of `nsolve` with one vector each of equations, variables, and initial values.

**Comment by jverzani** [comment]
There isn't a special method for nsolve for arrays. (It just gets the method specialized on the first argument being of type `Sym` exported.) Rather, unless an interface is provided later on, you would need to defer to `sympy.nsolve`, which is called like:

```
sympy.nsolve([z1^2-1, z1+z2z1-2], (z1,z2z1), (1,1))
```

Note, tuples for the arguments, not vectors. As passing `[1,1]` causes an error: 
```
TypeError('cannot create mpf from array([1, 1], dtype=int64)')
```

**Comment by mzaffalon** [comment]
Would it make sense to add a test, so that there is a least a reference use?

**Comment by steinQF** [comment]
Yes. It would make even more sense to add (even more) documentation. But I fear it's alot of work...

If that helps: I'm in the middle of adding a Section on using SymPy for solving a mode-matching problem using the ray transfer matrix formalism, to the documentation of https://github.com/ngedwin98/ABCDBeamTrace.jl so maybe there will be an example of usage in that packages' docs somewhen. It might first appear on my fork (https://github.com/Quantum-Factory/ABCDBeamTrace.jl) but even there, I haven't pushed this work-in-progress yet. I can reference this issue in the PR, if that's of any interest.

Speaking of work: Thanks alot for the support, and even more for providing this package!

**Comment by jverzani** [comment]
yes, a test is a good idea. I'll leave this open as a reminder.

**Comment by mzaffalon** [comment]
@steinQF would you like to add the test?

**Comment by steinQF** [comment]
Sure, I'll add the test tomorrow.

**Comment by steinQF** [comment]
@mzaffalon I'm afraid I don't know how to add the test because I cannot seem to run the existing tests in julia v1.1. The package manager command `test` leads to the complaint `ERROR: trying to test unnamed project`. Adding the dependencies manually (without regard to their version because I don't know how to specify these without creating a file `Project.toml`) leads to what seems like a PyCall-version-incompatibility after `include("src/SymPy.jl")`:

```
ERROR: LoadError: InitError: MethodError: no method matching copy!(::PyCall.PyObject, ::SymPy.Sym)
Closest candidates are:
  copy!(::PyCall.PyObject, ::PyCall.PyObject) at /home/steinb/.julia/packages/PyCall/ttONZ/src/PyCall.jl:165
```

Sorry to be such a bother rather than a help regarding the test!
