### ISSUE TITLE
Parsing problem?

### ISSUE THREAD

**Issue by edljk** [JuliaPy/SymPy.jl#283]
I am surprised by the result of
```julia
using SymPy
x = symbols("x");
xsqr = Sym("x^2");
diff(xsqr, x)
0
```
whereas 
```julia
xsqr  = x^2;
diff(xsqr, x)
2⋅x
```

is ok..
Should I convert a string into an expression in an another way?

**Comment by jverzani** [comment]
Compare:
```
julia> Sym("x^2")
x²

julia> sympy.sympify("x^2")
 2
x 
```

The latter is what I think you want. The former creates a variable not an expression. However, I'd recommend building up the expression rather than rely on sympify to do it for you.

**Comment by edljk** [comment]
Perfect, thanks!
