### ISSUE TITLE
isequal when multiplying with a float

### ISSUE THREAD

**Issue by david-pl** [JuliaPy/SymPy.jl#290]
Multiplying a `SymPy` variable by `1` (integer) is not the same as multiplying it by `1.0` (float) as this simple bit of code illustrates:
```julia
using SymPy
@vars x
x == 1*x # true
x == 1.0*x # false
```
Is this supposed to be like this? As in Julia `1.0 == 1` is `true`, I would expect the same for the above.

**Comment by jverzani** [comment]
You'd have to take it up with the python side, as this isn't anything decided by this package. There is a difference in storage types, but I was surprised by the comparison of `Sym(1.0)` with `Sym(1)` being true. However one is simplified whereas one is left as a product.

```
julia> using SymPy

julia> Sym(1).__class__
PyObject <class 'sympy.core.numbers.One'>

julia> Sym(1.0).__class__
PyObject <class 'sympy.core.numbers.Float'>

julia> Sym(1.0) == Sym(1)
true

julia> @vars x
(x,)

julia> Sym(1.0) *x == Sym(1) * x
false

julia> (Sym(1)*x).__class__
PyObject <class 'sympy.core.symbol.Symbol'>

julia> (Sym(1.0)*x).__class__
PyObject <class 'sympy.core.mul.Mul'>
```

**Comment by jverzani** [comment]
Yeah, maybe I closed this too early. 

I noticed `==` dispatches to PyCall's sense of equality, but not necessarily SymPy's which has:

```
julia> a = Sym(1)*x
x

julia> b = Sym(1.0)*x
1.0⋅x

julia> sympy.Eq(a, b)
True
```
