### ISSUE TITLE
System of differential equations

### ISSUE THREAD

**Issue by otobrzo** [JuliaPy/SymPy.jl#291]
I am trying to solve the system of two differential equation and I got this error:

_MethodError: no method matching dsolve(::Array{Sym,1})
Closest candidates are:
  dsolve(!Matched::Sym, !Matched::Any...; ics, kwargs...) at /home/otobrzo/.julia/packages/SymPy/wd4d9/src/mathfuns.jl:119_

The error seems to be the same as in 
[previous report back in 2015](https://groups.google.com/forum/#!topic/julia-users/DzYUVEkPQQY)

```

using SymPy

t, m, kappa1, kappa2, k, omega = Sym("t, m, kappa1, kappa2, k, omega")

x = SymFunction("x")
y = SymFunction("y")

diffeq1 = Eq(diff(x(t),t,2) + kappa1/m*x(t) -k/m*y(t) + k/m*x(t))
diffeq2 = Eq(diff(y(t),t,2) + kappa2/m*x(t) +k/m*y(t) - k/m*x(t))


display(diffeq1)
display(diffeq2)

eqs = [Eq(diff(x(t),t,2) + kappa1/m*x(t) -k/m*y(t) + k/m*x(t)), Eq(diff(y(t),t,2) + kappa2/m*x(t) +k/m*y(t) - k/m*x(t))]


dsolve(eqs)
```

**Comment by jverzani** [comment]
Closed by #292; in the interim (before a release is tagged), you can use the qualified `sympy.dsolve`. Thanks!
