### ISSUE TITLE
using Sympy in julia fails

### ISSUE THREAD

**Issue by yakoubsohn** [JuliaPy/SymPy.jl#297]
i joint the following error message.
Thanks for help
yak@mip.ups-tlse.fr

julia> using SymPy
ERROR: InitError: PyCall.PyError("PyImport_ImportModule\n\nThe Python package sympy could not be found by pyimport. Usually this means\nthat you did not install sympy in the Python version being used by PyCall.\n\nPyCall is currently configured to use the Python version at:\n\n/usr/bin/python3\n\nand you should use whatever mechanism you usually use (apt-get, pip, conda,\netcetera) to install the Python package containing the sympy module.\n\nOne alternative is to re-configure PyCall to use a different Python\nversion on your system: set ENV[\"PYTHON\"] to the path/name of the python\nexecutable you want to use, run Pkg.build(\"PyCall\"), and re-launch Julia.\n\nAnother alternative is to configure PyCall to use a Julia-specific Python\ndistribution via the Conda.jl package (which installs a private Anaconda\nPython distribution), which has the advantage that packages can be installed\nand kept up-to-date via Julia.  As explained in the PyCall documentation,\nset ENV[\"PYTHON\"]=\"\", run Pkg.build(\"PyCall\"), and re-launch Julia. Then,\nTo install the sympy module, you can use `pyimport_conda(\"sympy\", PKG)`,\nwhere PKG is the Anaconda package the contains the module sympy,\nor alternatively you can use the Conda package directly (via\n`using Conda` followed by `Conda.add` etcetera).\n\n", PyCall.PyObject(Ptr{PyCall.PyObject_struct} @0x00007f4e84eb37c0), PyCall.PyObject(Ptr{PyCall.PyObject_struct} @0x00007f4e83dd4668), PyCall.PyObject(Ptr{PyCall.PyObject_struct} @0x0000000000000000))
Stacktrace:
 [1] pyimport(::String) at /home/yak/.julia/packages/PyCall/ttONZ/src/PyCall.jl:544
 [2] pyimport_conda(::String, ::String, ::String) at /home/yak/.julia/packages/PyCall/ttONZ/src/PyCall.jl:702
 [3] pyimport_conda at /home/yak/.julia/packages/PyCall/ttONZ/src/PyCall.jl:701 [inlined]
 [4] __init__() at /home/yak/.julia/packages/SymPy/wd4d9/src/SymPy.jl:99
 [5] _include_from_serialized(::String, ::Array{Any,1}) at ./loading.jl:685
 [6] _require_search_from_serialized(::Base.PkgId, ::String) at ./loading.jl:765
 [7] _require(::Base.PkgId) at ./loading.jl:990
 [8] require(::Base.PkgId) at ./loading.jl:911
 [9] require(::Module, ::Symbol) at ./loading.jl:906
during initialization of module SymPy

**Comment by mzaffalon** [comment]
It looks like the problem is a missing Python install. What Julia version do you have and how did you install Python?

**Comment by yakoubsohn** [comment]
Le 2019-09-08 14:49, Michele Zaffalon a écrit :
> It looks like the problem is a missing Python install. What Julia
> version do you have and how did you install Python?

Python 2.7.15+

**Comment by mzaffalon** [comment]
Can you please provide all the information?

**Comment by yakoubsohn** [comment]
I gave all the information.
What do you want more?

**Comment by mzaffalon** [comment]
Julia version and how you installed Python, which is the text you quoted

**Comment by yakoubsohn** [comment]
Ubuntu 18.04.3 LTS
julia version 1.2.0
Python 2.7.15+ installed by default by Ubuntu

Le 2019-09-09 20:16, Michele Zaffalon a écrit :

**Comment by mzaffalon** [comment]
The preferred way is to use [Conda.jl](https://github.com/JuliaPy/Conda.jl): can you give it a try? I have never had a problem with this installation.

By the way, I am not sure whether `sympy.py` works on Python 2.7.

**Comment by Qfl3x** [comment]
`sympy` is deprecated on Python2. Please install Python3 and get `sympy` there.

**Comment by yakoubsohn** [comment]
In fact i have resolved this problem installing the module python-sympy from the synaptic of ubuntu
many thanks for your help
