### ISSUE TITLE
documentation issue - `roots()` function 

### ISSUE THREAD

**Issue by 00krishna** [JuliaPy/SymPy.jl#300]
Hello Maintainers. 

I ran into a little issue with the documentation on the `roots()` function. I think I can submit a PR to add some additional explanation or examples to the `roots()` function to show how to use the function. I ran into a bit of confusion since there was no help documentation on the function.

I was trying to get the roots of a 5th degree polynomial with a constant. In this code, `r` is meant to be a constant. So some code like:
```
using SymPy
@vars x, r
roots(r*x - x^3 + x^5)
```

But I got an error that said `raise PolynomialError('multivariate polynomials are not supported')`, which I can understand has to do with the `r` being seen as a variable and not as a constant. 

Someone suggested I use `solve` instead, and the following code worked:

`solve(r*x - x^3 + x^5, x)`

So then I tried the same code with the `roots` function and it also worked. 

`roots(r*x - x^3 + x^5, x)`

I could submit a PR to add some additional documentation to that function if the Maintainers think it would be helpful.

**Comment by jverzani** [comment]
In general, that would be helpful. But in this case, the way `roots` makes it into the system is a bit convoluted. It is generated automatically in `import_sympy` and written to a file `importexport.jl`. The documentation would be wiped clean the next time that gets run. To do it properly would take pulling the function out and defining and documenting it as with some other functions that don't lend themselves to the automated approach.

I'd suggest searching for the SymPy (python) module interface for help, as that is the expected flow.

**Comment by 00krishna** [comment]
@jverzani Oh that makes sense. I get where you are coming from. So I will just follow the behavior of python Sympy. Sounds good, and thanks for responding.
