### ISSUE TITLE
Definition of sind,cosd ... in SymPy v1.0.7

### ISSUE THREAD

**Issue by llffyy2971** [JuliaPy/SymPy.jl#304]
In SymPy v1.0.7  ,sind(x), cosd(x),... etc. in mathfuns.jl (line 31) are defined as sin(PI * ex). I think it should be sin (PI / 180 * ex). which one is correct?

degree_variants = (:sind, :cosd, :tand, :cotd, :secd, :cscd,

                   :asind, :acosd, :atand, :acotd, :asecd, :acscd)

for  methvar in degree_variants

    meth = Symbol(String(methvar)[1:end-1])

    @eval begin

        (Base.$methvar)(ex::SymbolicObject) = ($meth)(PI*ex)     ## (PI/180*ex)???

    end

end

**Comment by jverzani** [comment]
Yikes, that seems wrong. Would you be interested in creating PR with a few tests?

**Comment by llffyy2971** [comment]
Sorry, I'm not a native speaker, and I can not catch the exact meanings of "creating PR with a few test". But I will show two examples of sind and cosd function without and with the term /180.

1, When x->0, limit(sind(x)/x) has an analytic solution: limit(sind(x)/x)=limit(sin(pi/180 * x)/x)=(sin(pi/180 * x))'/x'=pi/180 * cos(pi/180 * x)/1=pi/180

SymPy solution:

without /180
julia> @vars x real=true
(x,)
julia> limit(sind(x)/x,x=>0)
π     ## wrong!!!

with /180
julia> limit(sind(x)/x,x=>0)
 π
───            ## right!!!
180

2, When x->90, limit(cosd(x)/(x-90)) has an analytic solution: limit(cosd(x)/(x-90))=limit(cos(pi/180 * x)/(x-90))=(cos(pi/180 * x))'/(x-90)'=-pi/180 * sin(pi/180 * x)/1=-pi/180

SymPy solution:

without /180
julia> limit(cosd(x)/(x-90),x=>90)
∞    ##wrong!!!

with /180
julia> limit(cosd(x)/(x-90),x=>90)
-π
───     ##right!!!
180

**Comment by jverzani** [comment]
Sorry, There was  definitely an error. I just wanted to know  if you wanted to fix it.  No need now, I have a PR (pull request) that addresses the issue. It will be merged and a new version  will appear today.  Thanks for your help.

**Comment by llffyy2971** [comment]
Thank you Jverzani, I am not a developer,  even I am not a real user. I am learning this language. I found this bug by chance and some one told me I can report this problem here.
