### ISSUE TITLE
sympy.Matrix needs comment

### ISSUE THREAD

**Issue by jverzani** [JuliaPy/SymPy.jl#314]
The construct `sympy.Matrix([[1,2,3],[2,3,1]])` (appearing in the tutorial on matrices) is not valid anymore (atleast with `sympy.__version__ # 1.5.1`). Specifying the matrix with `julian` syntax does work. The tutorial should be updated.

**Comment by waldyrious** [comment]
@jverzani this was fixed in #317, right?

**Comment by jverzani** [comment]
Yes, that's right. I should have added the issue number. Thanks.
