### ISSUE TITLE
UndefVarError: Dummy not defined

### ISSUE THREAD

**Issue by lucasvreis** [JuliaPy/SymPy.jl#319]
If I do this:
```julia
dummy = sympy.Dummy
# Symbolic differentiation of functions
function D(f)
    x = dummy("x")
    lambdify(diff.(f(x), x), (x,))
end
```
And then this:
```julia
D(t -> t^2)(1)
```

I get `UndefVarError: Dummy not defined`. It works fine, however, if the result of differentiation has no symbols, like `D(t -> t)(1)`.

**Comment by lucasvreis** [comment]
I've tested using the stable version of the package in Julia 1.2.0 and 1.3.1, and both reproduce the error.

**Comment by jverzani** [comment]
Thanks, this is an issue with `lambdify` that can be addressed.
