### ISSUE TITLE
Lambdify problem with expression containing undefined E (which should be reckognized as exp(1))

### ISSUE THREAD

**Issue by jmbeckers** [JuliaPy/SymPy.jl#328]
There seems to be a problem with the variable "E" (e) : the minimal example I was able to construct and included hereafter works well for the first example (@show ex3 provides an expression with some exp(1) etc which lamdify well). In the second example @show ex3 reveals there are some E in the expression which do NOT lambdify is the sense that once I try to evaluate the function I get "UndefVarError: e not defined". 

Any clue how I could try to get around that problem?

using SymPy
C=SymFunction("C")
x=symbols("x", real=true,positive=true)

diffeq = Eq(diff(C(x), x, 2) -C(x) , 0)
ex = dsolve(diffeq, C(x))
ex1 = ex.rhs()
CC1=solve(ex1(x => 0)-1, Sym("C1"))
ex2 = ex1(Sym("C1") => CC1[1])
CC2=solve(ex2(x => 1)-0, Sym("C2"))
ex3 = ex2(Sym("C2") => CC2[1])
@show ex3

myf=lambdify(ex3)
myf(0.1)

diffeq = Eq(diff(C(x), x, 2) -C(x) , 0)
ex = dsolve(diffeq, C(x))
ex1 = ex.rhs()
CC1=solve(ex1(x => 0)-2, Sym("C1"))
ex2 = ex1(Sym("C1") => CC1[1])
CC2=solve(ex2(x => 1)-3, Sym("C2"))
ex3 = ex2(Sym("C2") => CC2[1])
@show ex3

myf2=lambdify(ex3)
myf2(0.1)

**Comment by jverzani** [comment]
Thanks! This was coded back before `e` was  in `MathConstants` and hadn't been caught since.
