### ISSUE TITLE
ZeroDivisionError in definite integral; variable integration bounds

### ISSUE THREAD

**Issue by anshuchen** [JuliaPy/SymPy.jl#342]
I'm integrating a bivariate normal PDF over its two variables, `a` and `n`. There is a third variable `p` that I want to include in the integration bounds, but SymPy throws a ZeroDivisionError when I try this. 

Running the following,

```
using SymPy
σ = 0.2
ρ = -0.9
f(a,n) = (1/(2*π*(σ^2)*sqrt(1-ρ^2)))*exp(-(1/(2*(1-ρ^2)))*((a^2)/σ^2 + (n^2)/σ^2 -((2*ρ*a*n)/σ^2)))
@vars a n p
integrate(a*f(a,n), (n, -oo, p*a), (a, -oo, oo))
```

Yields 

`ERROR: PyError ($(Expr(:escape, :(ccall(#= C:\Users\Anshu\.julia\packages\PyCall\zqDXB\src\pyfncall.jl:43 =# @pysym(:PyObject_Call), PyPtr, (PyPtr, PyPtr, PyPtr), o, pyargsptr, kw))))) <class 'ZeroDivisionError'>`

Weirdly, the following attempts run with no issues:

Just integrating f, not a*f:
`integrate(f(a,n), (n, -oo, p*a), (a, -oo, oo))`

Replacing p with a constant 1:
`integrate(a*f(a,n), (n, -oo, a), (a, -oo, oo))`

I'm using SymPy 1.5.1 on Julia 1.4.0.

**Comment by mzaffalon** [comment]
There is no SymPy 1.5.1: the newest tagged version is 1.0.19. 

Using Julia 1.4.0 and SymPy 1.0.19, the integral of `a*f(a,n)` returns an non-evaluated integral, not the error message that you report.

**Comment by jverzani** [comment]
Closing, please reopen if need be.
