### ISSUE TITLE
Define isreal(x::Sym)

### ISSUE THREAD

**Issue by olof3** [JuliaPy/SymPy.jl#350]
`isreal` is currently not defined for `Sym` objects.

Something like
```
Base.isreal(a) = a.is_real
```
seems to make sense to me. Any thoughts?

**Comment by jverzani** [comment]
In `generic.jl` I found  `Base.isreal(x::Sym) = is_(:real, x)`. It seems to work:

```
julia> @vars x real=true
@(x,)

julia> @vars y
(y,)

julia> isreal(x)
true

julia> isreal(y)
false

```

I'm closing, but please  do reopen  if  there is a case this isn't catching but should.

**Comment by olof3** [comment]
Thanks, seems to work. Not sure what mistake I made.
