### ISSUE TITLE
Problems with promotion and conversion of (Bool, Sym)

### ISSUE THREAD

**Issue by olof3** [JuliaPy/SymPy.jl#351]
The following two issues prevent doing something like

```
kron(I(2), [Sym("a") 1; 2 1])
```

#### 1.
`true*Sym(2)` doesn't work
(`true*Sym("a")` does work for however)

Defining one of the following seems to solve this.
```
Base.convert(::Type{Sym}, x::Bool) = (x ? Sym(1) : Sym(0))
Base.convert(::Type{Sym}, x::Bool) = convert(Sym, Int(x))
```
Does this seems reasonable, or is this supposed to bea feature of how SymPy handles booleans?

#### 2.
Another issue is that `Base.promote_op(*, Sym, Bool)` returns `Any`.
(`Base.promote_op(*, Sym, Int)` returns `Sym` as expected though)

I don't have any suggestions for how to fix this though.

**Comment by jverzani** [comment]
Currently, with `true*Sym(2)`, `true` promotes  to  `True`:
```
promote(Sym(2), true)
```
And then SymPy's `x.__mul__(y)` takes  over. It would be  great if that method respected  booleans  as  0,1  values, alas.

I'm  not  sure  how to  address this short of defining a `*(x::Bool,  x::Sym)` method. Let me try that,  and  see  how  far  it goes.

**Comment by olof3** [comment]
Thanks for fixing this so quickly! Seems to work alright.

Not sure about the added regression tests though. Maybe I'm missing something obvious, but it seems like you are just testing operations with julia's built-in types?

**Comment by jverzani** [comment]
Oops.  Thanks.  Those should have Sym.
