### ISSUE TITLE
SymPy exports module `Q`

### ISSUE THREAD

**Issue by olof3** [JuliaPy/SymPy.jl#354]
This is a bit annoying since `Q` is quite nice letter for various matrices and other objects.

```julia
julia> using SymPy
julia> Q = [2 1; 1 3]
ERROR: cannot assign a value to variable SymPy.Q from module Main
```

Would it be reasonable to just avoid exporting `Q`? With or without deprecating it first.

I couldn't immediately find any other instances that are as problematic as this one, but I guess it could be worthwhile to have a second look.

**Comment by jverzani** [comment]
I would  think  we  could deprecate  `Q`  from  being  exported. `N` is a  different  matter, as it has a pretty  common usage. I would think  offering  a unicode  alternative  and  `SymPy.Q`. What is somewhat cumbersome,  is `sympy.Q` doesn't offer  an alternative. Do you want to put  together a PR? If not, I'll get  to  it at  some  point  in  the near term.

**Comment by olof3** [comment]
I think you have a better vision of how to fix this. No hurry on my part.
