### ISSUE TITLE
linsolve fails

### ISSUE THREAD

**Issue by melonedo** [JuliaPy/SymPy.jl#357]
When I was trying the tutorials in examples/solvers.md, I find these are probably broken. 
solve seems to be good:
```julia
julia> @vars x y z
julia> solve([x + y + z - 1, x + y + 2*z - 3 ], (x, y, z))
Dict{Any,Any} with 2 entries:
  z => 2
  x => -y - 1
```
linsolve produces an empty set (this is also shown in the notebook version of tutorial):
```julia
julia> linsolve([x + y + z - 1, x + y + 2*z - 3 ], (x, y, z))
∅
```
solveset can't even run:
```julia
solveset([x + y + z - 1, x + y + 2*z - 3 ], (x, y, z))
ERROR: MethodError: no method matching solveset(::Array{Sym,1}, ::Tuple{Sym,Sym,Sym})
Closest candidates are:
  solveset(::SymPy.SymbolicObject, ::Any...; kwargs...) at C:\Users\melonedo\.julia\packages\SymPy\QNFlL\src\importexport.jl:96
Stacktrace:
 [1] top-level scope at REPL[17]:1
```
Are there any caveats in using this module?

**Comment by jverzani** [comment]
Thanks for pointing these out. I need  to integrate  the examples into the testing framework, as    changes  to the  underlying   `sympy` package  can necessitate  changes  to this package. I'll look into these specific issues and  address. There certainly have  been changes.
