### ISSUE TITLE
Addition/subtraction of Matrix{Sym} and UniformScaling gives Matrix{Any}

### ISSUE THREAD

**Issue by olof3** [JuliaPy/SymPy.jl#359]
```julia
@vars a b
typeof([a 1; b b] + I)
```
gives `Matrix{Any}` and not `Matrix{Sym}` 

Multiplication seems to work though.

Not sure if the problem is with  `SymPy.jl` or that the logic in `LinearAlgebra` is too fragile?

**Comment by jverzani** [comment]
Thanks, it  comes down  to

```
Base._return_type(+, (Sym, typeof(I))) #  Any
Base._return_type(*, (Sym, typeof(I)))  # UniformScaling
```

I'm  not sure how to hint that the  first  return  type should be  `Sym`. Do you have any idea? That would  be the right fix.  Otherwise, we could just define  through `A .+ I.λ`.

**Comment by olof3** [comment]
Nope, I don't really have any good ideas, I'm afraid.

`eltype(symbols("a") + I)` gives `Sym` and since that seems to work I feel like it should be possible to infer the correct type so not sure what is broken. The code for the type inference is a bit daunting to me.

Note sure what you mean by `A .+ I.λ`?   I guess `A .+ λI != A .+ I.λ`

**Comment by jverzani** [comment]
Yes, I'm not sure what is broken or how to fix the promotion. As you see,  but unfortunately `Base._return_type(+, (eltype(symbols("a")), eltype(I)))` is checked and that gives `Any`. I think adding the method 

`Base.:+(A::AbstractMatrix, I::UniformScaling) = (n=LinearAlgebra.checksquare(A); A .+ I.λ*I(n))`

will work as desired, as `I.λ*I(n)` creates an object that dispatches differently than `I` alone (the way `λ*I` is stored allows the scalar to be found through `I.λ`).
