### ISSUE TITLE
Where is factor_list?

### ISSUE THREAD

**Issue by baggepinnen** [JuliaPy/SymPy.jl#380]
Here
https://juliahub.com/docs/SymPy/KzewI/1.0.31/Tutorial/simplification/#Polynomial/Rational-Function-Simplification-1
is mentioned a function `factor_list`, but I can't seem to find it
```
julia> SymPy.factor_list
ERROR: UndefVarError: factor_list not defined
Stacktrace:
 [1] getproperty(::Module, ::Symbol) at ./Base.jl:26
 [2] top-level scope at none:1
```
on latest released version

**Comment by jverzani** [comment]
Most functionality is in the python object `sympy` not the Julia module `SymPy`, so the function is called by `sympy.factor_list(...)`.
