### ISSUE TITLE
How to generate latex code with this package?

### ISSUE THREAD

**Issue by ChasingZenith** [JuliaPy/SymPy.jl#382]
I am a MATLAB user. I really hope that I can use a function **latex** like I can do in MATLAB. 

Now I am using this workaround with the followint code, which get latex function form Python/sympy
```julia
using PyCall
latex = pyimport("sympy.printing.latex")
latex = latex.latex
```
There are some other questions.

The symbol will be render if it is the last line in the code block in Jupyter notebook. I am finding a function that I can render this symbols mannually when I want, say, in a loop. Can I do that?

I am also wondering where can I find the document for this package.

Thanks in advance!

**Comment by jverzani** [comment]
Welcome to Julia!

That is one way to get latex output. In Julia, the `display` function is called behind the scenes on the last value evaluated with a mimetype to show the values in the notebook. You can hook into that, as follows, to get at what you want:

```
@vars x
display("text/latex", x^x)
for n in 1:5
    display("text/latex", diff(x^x, (x, n)))
end
```

As for documentation, you can try: https://juliahub.com/docs/SymPy/KzewI/1.0.31/
That will show package specific documentation. However, the vast majority of usefulness of this package is that it just interfaces julia users to the underlying Python package. For those uses, the SymPy documentation should be consulted.

**Comment by ChasingZenith** [comment]
Thank you for your instant response!

I want to get a string that I can paste into my latex source code, so I can use it directly.

While adding a `display` function is a solution that I can display it in the Jupyter notebook. That is useful when I want to debug.

It's so good to know that there is such great documentation. Is there any hyperlink in this repository pointing to that? I think that will be really helpful for all SymPy.jl users.

**Comment by jverzani** [comment]
I should have said that you can call the`latex` function you found through `SymPy.latex` or even `sympy.latex`. It was exported at one time, but came into conflict with other packages so it needs to be qualified.

To mirror the `display` command, you could use `show(io, "text/latex", expression)`. For example,

```
julia> show(stdout, "text/latex", diff(x^x,(x,2)))
\begin{equation*}x^{x} \left(\left(\log{\left(x \right)} + 1\right)^{2} + \frac{1}{x}\right)\end{equation*}
```

To get a string you can use and `IOBuffer` or this trick: `sprint(io -> show(io, "text/latex", expression))`.

As for the doc link, at one point I had default documentation for methods. But some changes broke that and I never figured out how to get it back. I should add a link to the README with the general entry point. If you wanted to put in a PR for that, I'd be appreciative.

**Comment by ChasingZenith** [comment]
I think the best way to import latex function may be using
```julia
using SymPy
latex = sympy.latex  # SymPy.latex  is not working in this case
```

**Comment by jverzani** [comment]
Yes, there might be a difference, the defn is here:

```
latex(x::Sym) = sympy.latex(x)
```

So `SymPy.latex` is narrowed to `Sym` objects. Probably best to just remove this definition.

**Comment by ChasingZenith** [comment]
Thank you for your exposition.
In my usage this week, I think using `sympy.latex` directly work quite well for me. Sometimes, I need to print latex code for symbolic matrices. It seems that `SymPy.latex` can not do this for me. Maybe just use `sympy.latex` is enough. :)

**Comment by jverzani** [comment]
For matrices, you can convert to a symbolic matrix (instead of a matrix of symbolic objects):

```
M = [x 1; 1 x]
sympy.latex(convert(SymMatrix, M))
```

**Comment by jverzani** [comment]
Closing. Reopen if you didn't get the answer you were looking for.
