### ISSUE TITLE
Issue with SymPy installation on julia 

### ISSUE THREAD

**Issue by PPorras** [JuliaPy/SymPy.jl#386]
Hi everyone:

I have the following issue when I try to install SymPy on Julia. Do you have a some suggestion? 
I attach the lines that I get the julia prompt.

`(v1.0) pkg> add SymPy
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package RecipesBase [3cdcf5f2]:
 RecipesBase [3cdcf5f2] log:
 ├─possible versions are: [0.4.0, 0.5.0, 0.6.0, 0.7.0, 0.8.0, 1.0.0-1.0.2, 1.1.0-1.1.1] or uninstalled
 ├─restricted by compatibility requirements with SymPy [24249f21] to versions: [0.4.0, 0.5.0, 0.6.0, 0.7.0, 1.0.0-1.0.2, 1.1.0-1.1.1]
 │ └─SymPy [24249f21] log:
 │   ├─possible versions are: [0.7.0, 0.8.0-0.8.4, 0.9.0, 1.0.0-1.0.32] or uninstalled
 │   └─restricted to versions * by an explicit requirement, leaving only versions [0.7.0, 0.8.0-0.8.4, 0.9.0, 1.0.0-1.0.32]
 └─restricted by compatibility requirements with Plots [91a5bcdd] to versions: 0.8.0 — no versions left
   └─Plots [91a5bcdd] log:
     ├─possible versions are: [0.12.1-0.12.4, 0.13.0-0.13.1, 0.14.0-0.14.2, 0.15.0-0.15.1, 0.16.0, 0.17.0-0.17.4, 0.18.0, 0.19.0-0.19.3, 0.20.0-0.20.6, 0.21.0, 0.22.0-0.22.5, 0.23.0-0.23.2, 0.24.0, 0.25.0-0.25.3, 0.26.0-0.26.3, 0.27.0-0.27.1, 0.28.0-0.28.4, 0.29.0-0.29.9, 1.0.0-1.0.14, 1.1.0-1.1.4, 1.2.0-1.2.6, 1.3.0-1.3.7, 1.4.0-1.4.4, 1.5.0-1.5.9, 1.6.0-1.6.12, 1.7.0-1.7.3, 1.8.0-1.8.1, 1.9.0-1.9.1] or uninstalled
     └─restricted to versions 0.29.9 by an explicit requirement, leaving only versions 0.29.9`

**Comment by jverzani** [comment]
I expect #387 to address this.
