### ISSUE TITLE
Pluto.jl support?

### ISSUE THREAD

**Issue by schneiderfelipe** [JuliaPy/SymPy.jl#400]
Hi, I got the following when defining a symbolic variable inside Pluto.jl:

![Screenshot from 2021-01-03 19-36-11](https://user-images.githubusercontent.com/37125/103490504-fdca7a00-4dfa-11eb-8a6c-e9de34139355.png)

The MathJax error says "`\begin` is only supported in math mode." This is probably due to the `\text` above, right?

The following code reproduces the behavior:

```julia
using SymPy

x = symbols("x")
```

(`@syms x` shows the same output.)

**Comment by jverzani** [comment]
Hmm, I can confirm. I guess the display of latex differs between pluto and IJulia. Here is an immediate workaround via Markdown. If this works, I might have to figure out how to put this as the default for SymPy assuming it doesn't break IJulia

```
function Base.show(io::IO, M::MIME"text/latex", x::SymPy.SymbolicObject) 
	out = Markdown.parse("``$(sympy.latex(x, mode="equation*"))``")
	show(io,  M, out)
end
```

**Comment by jverzani** [comment]
Thanks for reporting! I put in this fix. When merged, you'll just need to update SymPy.

**Comment by schneiderfelipe** [comment]
@jverzani Thanks a lot!
