### ISSUE TITLE
Easily plotting Taylor series

### ISSUE THREAD

**Issue by schneiderfelipe** [JuliaPy/SymPy.jl#402]
The following example produces a nice plot (see screenshot below):

```julia
let f(x) = 1/x, n = 10
	a, b = 0.5, 3
	x₀ = 1
	taylor = series(f(x), x, x₀, n + 1).removeO()
	
	plot(f, a, b; label="f(x)")
	plot!(taylor, a, b; label="\$f_$n(x)\$")
	ylims!((0, 3.5))
end
```

![Screenshot from 2021-01-08 00-55-17](https://user-images.githubusercontent.com/37125/103972697-3dbb9500-514c-11eb-977a-9e2687b1e991.png)

But two things to note:
1. The series plot looks jagged, how can this be improved?
2. Removing the `.removeO()` piece gives a **"Order not defined" error**:

```
UndefVarError: Order not defined

    ##601(::Float64)@none:0
    #invokelatest#1@essentials.jl:712[inlined]
    invokelatest@essentials.jl:711[inlined]
    #89@lambdify.jl:215[inlined]
    (::Base.var"#64#65"{RecipesPipeline.var"#11#12"{Symbol},SymPy.var"#89#90"{SymPy.var"###601"}})(::Float64)@operators.jl:859
    (::PlotUtils.var"#27#29"{Base.var"#64#65"{Base.var"#64#65"{RecipesPipeline.var"#11#12"{Symbol},SymPy.var"#89#90"{SymPy.var"###601"}},RecipesPipeline.var"#13#14"{Symbol}}})(::Float64)@adapted_grid.jl:46
    _broadcast_getindex_evalf@broadcast.jl:631[inlined]
    _broadcast_getindex@broadcast.jl:604[inlined]
    getindex@broadcast.jl:564[inlined]
    copy@broadcast.jl:854[inlined]
    materialize@broadcast.jl:820[inlined]
    #adapted_grid#26(::Int64, ::Float64, ::typeof(PlotUtils.adapted_grid), ::Base.var"#64#65"{Base.var"#64#65"{RecipesPipeline.var"#11#12"{Symbol},SymPy.var"#89#90"{SymPy.var"###601"}},RecipesPipeline.var"#13#14"{Symbol}}, ::Tuple{Float64,Float64})@adapted_grid.jl:57
    adapted_grid(::Function, ::Tuple{Float64,Float64})@adapted_grid.jl:16
    _scaled_adapted_grid(::Function, ::Symbol, ::Symbol, ::Float64, ::Int64)@user_recipe.jl:307
    macro expansion@user_recipe.jl:286[inlined]
    apply_recipe(::AbstractDict{Symbol,Any}, ::Function, ::Number, ::Number)@RecipesBase.jl:282
    _process_userrecipes!(::Plots.Plot{Plots.GRBackend}, ::Dict{Symbol,Any}, ::Tuple{SymPy.Sym,Float64,Int64})@user_recipe.jl:35
    recipe_pipeline!(::Plots.Plot{Plots.GRBackend}, ::Dict{Symbol,Any}, ::Tuple{SymPy.Sym,Float64,Int64})@RecipesPipeline.jl:69
    _plot!(::Plots.Plot{Plots.GRBackend}, ::Dict{Symbol,Any}, ::Tuple{SymPy.Sym,Float64,Int64})@plot.jl:167
    #plot!#134(::Base.Iterators.Pairs{Symbol,String,Tuple{Symbol},NamedTuple{(:label,),Tuple{String}}}, ::typeof(RecipesBase.plot!), ::Plots.Plot{Plots.GRBackend}, ::SymPy.Sym, ::Vararg{Any,N} where N)@plot.jl:158
    #plot!#133(::Base.Iterators.Pairs{Symbol,String,Tuple{Symbol},NamedTuple{(:label,),Tuple{String}}}, ::typeof(RecipesBase.plot!), ::SymPy.Sym, ::Vararg{Any,N} where N)@plot.jl:150
    top-level scope@Local: 7
```

Could the plotting of a series be made directly?

**Comment by jverzani** [comment]
Let me answer in reverse: `removeO` is needed to remove the "big Oh" term that SymPy computes. I don't know of what else to do, though *perhaps* this could be addressed in `lambdify` (which convert the sympy object into a julia function for plotting purposes. (I'll look into that.)

As for the jaggedness, I have no clue. The entire plot recipe just makes a function and passes that onto the Plots recipe pipeline. My **guess** is that it comes from the adaptive plotting algorithm which chooses a small set of points and refines as needed. (If you do not narrow with `ylims!` the taylor plot looks fine, as the function spikes, so you don't see those kinks.)

In this case, you could create a vector of `xs` and map them through `f`to get the ys:

e.g.:
```
xs = range(a,b, length=251)
tay = lambdify(taylor)
ys = tay.(xs)
plot!(xs, ys)
```

**Comment by jverzani** [comment]
In #403, I work around the 2nd issue, but the first is not really possible here, as the issue sits with Plots.

**Comment by schneiderfelipe** [comment]
Nice! Thanks!

As for the first issue, is it possible to construct a plot `@recipe` receiving a Taylor series (or any object having a big-O term, that is)?

**Comment by jverzani** [comment]
Sorry, that's the part I could fix. The other part (the kink) I can't.

**Comment by schneiderfelipe** [comment]
> Sorry, that's the part I could fix. The other part (the kink) I can't.

That's perfect, thanks a lot!
