### ISSUE TITLE
Matrix exponential of Matrix{Sym} and mulplication of SymMatrix

### ISSUE THREAD

**Issue by olof3** [JuliaPy/SymPy.jl#413]
```julia
@vars a
A = [1 0; 0 a]
```
I would like to compute the matrix exponential of `A`, but in order to do so it seems like I must convert it to `Sym` (not SymMatrix)?
```
B = exp(Sym(A))
```
which gives a `SymMatrix` (not Sym).
But then I am not sure how to work with these SymMatrices, it seems like normal multiplication doesn't work
```julia
julia> B * B
ERROR: MethodError: *(::SymMatrix, ::SymMatrix) is ambiguous.
```
So I guess there are multiple questions here?
1. Should it be possible to compute the matrix exponential of `Matrix{Sym}` directly?
2. exp of a Sym gives a SymMatrix ?!
3. How to multiply two `SymMatrix`

I guess that points 2 and 3 would not be so important if only `exp(::Matrix{Sym})` worked and returned the correct `Matrix{Sym}`.

**Comment by jverzani** [comment]
Thanks for pointing this out.

There is a method that could be added, namely, something like:
```
Base.exp(A::Matrix{Sym}) = A.exp()
```

where the key for your answer is you can all `A.exp()` on your matrix of symbolic objects `A`.

But you also found a bug in the multiplication of the `SymMatrix` objects.

**Comment by olof3** [comment]
Thanks, yes, that method seems like it would be convenient. At least if the idea is that one should primarily work with `Matrix{Sym}`. 

Not really sure what the relation between `SymMatrix` and `Matrix{Sym}`, and if one should be preferred over the other?

**Comment by jverzani** [comment]
Matrices of symbolic objects allow generic Julia code to be run, so I think that is better. To call the underlying SymPy methods, the dot notation is useful, as with `A.exp()`.

But SymPy provides both a `SymMatrix` and `ImmutableMatrix` class, so the package tries to provide a few tools to make working with those easier. As you see, they could be better supported and tested.

**Comment by jverzani** [comment]
This didn't get closed automatically. It seems like the issue was resolved.
