### ISSUE TITLE
Simplification page in the documentation has format problems

### ISSUE THREAD

**Issue by runjaj** [JuliaPy/SymPy.jl#448]
Hello,

the page about [Simplification](https://docs.juliahub.com/SymPy/KzewI/1.1.1/Tutorial/simplification/) in the documentation has format problems from the [Powers section](https://docs.juliahub.com/SymPy/KzewI/1.1.1/Tutorial/simplification/#Powers-1) to the end.

I think that the problem is the code example after the sentence: "However, the recommended way is to use @syms for symbol construction with assumptions:".

I think that this problem appeared in version 1.0.44. [Version 1.0.43](https://docs.juliahub.com/SymPy/KzewI/1.0.43/Tutorial/simplification/)  seems to be right, but without the new information.

Javier

**Comment by jverzani** [comment]
Thanks! Let me look.

**Comment by jverzani** [comment]
Closed by #449
