### ISSUE TITLE
Feature request: Add curried form of doit function

### ISSUE THREAD

**Issue by fatteneder** [JuliaPy/SymPy.jl#455]
Hi

I like to use the `subs` function when chaining operations with `|>`. Unfortunately, there is no such version for `doit`.
Here is a MWE with a curried version of it:

```julia
julia> @syms x f()
(x, f)

julia> D = Differential(x)
Differential(x)

julia> subs(D(f(x)), f(x), x)
d
──(x)
dx

julia> subs(D(f(x)), f(x), x).doit() # already available
1


julia> subs(D(f(x)), f(x), x) |> doit # to be implemented
1
```

The actual implementation is as simple as
```julia
doit(ex::T; deep::Bool=false) where {T<:SymbolicObject} = ex.doit(deep=deep)
```

Would you be interested in a PR for this?

**Comment by jverzani** [comment]
Sure that seem reasonable. Look forward to seeing it!
