### ISSUE TITLE
MatrixSymbol converstion to Matrix returns PyCall.PyObject

### ISSUE THREAD

**Issue by prittjam** [JuliaPy/SymPy.jl#462]
`U = sympy.Matrix(sympy.MatrixSymbol("U",2,2))
typeof(U) 
`

PyCall.PyObject

I can't do any matrix operations with it, unfortunately.

**Comment by jverzani** [comment]
Hmm, there is a convert method that isn't working here. Thanks for letting me know.

The sympy matrix operation work (e.g. `U.det()` will find the determinant) but Julia ones won't as the dispatch is setup for `Matrix{Sym}` types.

For this problem you can get a `Matrix{Sym}` object easy enough: `U.tolist()`. But there should be an automatic conversion (through `pytypemapping` or at least a `convert(Matrix{Sym}, U)` method defined.

**Comment by prittjam** [comment]
Thanks for the explanation! I can work around it for now.

**Comment by jverzani** [comment]
I think #463 closes this. Thanks for the report.
