### ISSUE TITLE
Piecewise not defined in SymPy

### ISSUE THREAD

**Issue by dgomezcastro** [JuliaPy/SymPy.jl#469]
I am using SymPy v1.1.6 over Julia v1.7.2 and the piecewise function does not seem to exist, either in lower case or upper case. 

It seems that it was implemented at some point: see [link](https://github.com/JuliaPy/SymPy.jl/issues/15)

```
julia> using SymPy

julia> x = Sym("x")
x

julia> piecewise((1, x < 1), (3, x >= 1))
ERROR: UndefVarError: piecewise not defined
Stacktrace:
 [1] top-level scope
   @ REPL[12]:1

julia> Piecewise((1, x < 1), (3, x >= 1))
ERROR: UndefVarError: Piecewise not defined
Stacktrace:
 [1] top-level scope
   @ REPL[15]:1
```

**Comment by mzaffalon** [comment]
```
sympy.Piecewise((1, Lt(x, 1)), (3, Ge(x, 1)))
```

**Comment by dgomezcastro** [comment]
Great! That works!. Is there some documentation for this? I cannot find any.

**Comment by jverzani** [comment]
Maybe the README, but it isn't very front and center. The basic idea is here:

> The basic usage follows these points:
> 
> generic methods from Julia and imported functions in the sympy namespace are called through fn(object)
> 
> SymPy methods are called through Python's dot-call syntax: object.fn(...)
> 
> Constructors, like sympy.Symbol, and other non-function calls from sympy are qualified with sympy.Constructor(...). Such qualified calls are also useful when the first argument is not symbolic.
> 
>

**Comment by dgomezcastro** [comment]
Perfect. Now I understood the logic. This is very useful.
