### ISSUE TITLE
broadcasting not typestable

### ISSUE THREAD

**Issue by jamblejoe** [JuliaPy/SymPy.jl#477]
Consider
```
julia> Base.Broadcast.combine_eltypes(+, (zero(Sym), zero(Sym)))
Any
```
coming from https://github.com/JuliaSparse/SparseArrays.jl/issues/75, where adding of sparse matrices with `Sym` type fails.

**Comment by jverzani** [comment]
Thanks! I have a PR to close this. Will tag sometime today if all the tests go through.
