### ISSUE TITLE
`subs` change the value of an expression

### ISSUE THREAD

**Issue by newptcai** [JuliaPy/SymPy.jl#479]
The following code in REPL is bit strange
```
julia> n = symbols("n")
n

julia> ans = 4^n-3^n-n*3^(n-1)
   n    n - 1      n
- 3  - 3     ⋅n + 4 

julia> println(subs(ans, (n,4)))
67

julia> println(ans)
nothing
```
How can substitute `n` by `4` turns `ans` into `nothing`?

**Comment by newptcai** [comment]
This is different from this behaviour
```
julia> ex = (x-y)*(x+2y)
(x - y)⋅(x + 2⋅y)

julia> println(subs(ex, (x, 3)))
(3 - y)*(2*y + 3)

julia> println(subs(ex, (y, 3)))
(x - 3)*(x + 6)

julia> println(ex)
(x - y)*(x + 2*y)
```

**Comment by mzaffalon** [comment]
`println` returns `nothing` and the variable `ans` is bound to the last result printed to the REPL. You should remove the `println` statement to get what you want, or even better, assign the result to a variable with a different name.

**Comment by newptcai** [comment]
> `println` returns `nothing` and the variable `ans` is bound to the last result printed to the REPL. You should remove the `println` statement to get what you want, or even better, assign the result to a variable with a different name.

:astonished: Oh the `ans` is a special variable! I didn't know that.
