### ISSUE TITLE
raise TypeError("Cannot convert expression to float") when assigning SymPy expression to an array

### ISSUE THREAD

**Issue by xiang-yu** [JuliaPy/SymPy.jl#481]
julia> @syms x, y
julia> xx = zeros(2,2)
julia> xx[1, 1] = x*y
ERROR: PyError (ccall(#= /Users/lixi307/.julia/packages/PyCall/ygXW2/src/conversions.jl:59 =# @pysym(:PyFloat_AsDouble), Cdouble, (PyPtr,), po)) <class 'TypeError'>
TypeError('Cannot convert expression to float')

If I define "xx" in type "Any"
xx = Array{Any}(undef, 2,2) 
julia> xx[1, 1] = x*y
x⋅y

However, I need a zeros instead of "undef". How to initialise a zero symbolic array using SymPy.jl?

**Comment by mzaffalon** [comment]
You should use `zeros(Sym,2,2)`:
```
julia> @syms x, y
(x, y)

julia> xx = zeros(Sym,2,2);

julia> xx[1, 1] = x*y
x⋅y
```

**Comment by xiang-yu** [comment]
Thanks. It works well.

**Comment by mzaffalon** [comment]
This issue can be closed.
