### ISSUE TITLE
sqrt(3) gives floating-point value instead of symbolic expression

### ISSUE THREAD

**Issue by ketch** [JuliaPy/SymPy.jl#493]
In Python:

<img width="191" alt="Screen Shot 2023-02-23 at 9 22 42 AM" src="https://user-images.githubusercontent.com/697763/220750325-38c18b29-ac9c-44c9-9b78-dc62cbc68d79.png">

In Julia:
<img width="290" alt="Screen Shot 2023-02-23 at 9 23 25 AM" src="https://user-images.githubusercontent.com/697763/220750422-d5bd20a0-a2d2-4b83-a843-5cf51c14e48d.png">

**Comment by jverzani** [comment]
Yeah, that is expected. `SymPy.sqrt` simply extends the base `sqrt` function for the `Sym` type (and friends). The method for `Int` remains unchanged, as you see. To get a symbolic value, you have `sqrt(Sym(3))` or `sqrt(sympify(3))` among other variants.

**Comment by ketch** [comment]
Thank you!
