### ISSUE TITLE
No SymPy.utilities

### ISSUE THREAD

**Issue by ketch** [JuliaPy/SymPy.jl#494]
Sympy (in Python) has a `utilities` module that includes, for instance, code generation tools.  Is it possible to access that from SymPy.jl?  So far, I haven't found a way.

More generally, is there a list somewhere of the Sympy functionality that is or is not included in SymPy.jl?

**Comment by jverzani** [comment]
Sorry, not sure how I missed this comment. You often can access the underlying library through the `sympy` object using dot notation. If that fails, you can import it with a command like: `aw = PyCall.pyimport("sympy.utilities.autowrap")`.

As for what is exposed, as little as possible. The basic math operators, the intersection of julia generic methods and matching (by name) sympy methods, a small selection of sympy commands that see wide use. I should have this documented, but if I do, I forgot where.

**Comment by jverzani** [comment]
In case this is still of interest. The soon to be merged as SymPy, SymPyPyCall, has `sympy.utilitities` directly accessible.
