### ISSUE TITLE
ordering of eigvals/eigvecs inconsistent with LinearAlgebra

### ISSUE THREAD

**Issue by aosidnf** [JuliaPy/SymPy.jl#495]
Specifically, the ordering is inconsistent such that it makes the common diagonalization behavior not work:
```
using LinearAlgebra
A=rand(2,2)
ξ=eigvecs(A)
λ=eigvals(A)
ξ*Diagonal(λ)*inv(ξ) -A # returns something close to zero ✅
```
but for a matrix of Syms,
```
using SymPy
As=Sym["a" "b"; "c" "d"]
ξs=eigvecs(As)
λs=eigvals(As)
ξs*Diagonal(λs)*inv(ξs) - As .|> simplify # returns something which isn't zero ❌
ξs*Diagonal([ λs[2],λs[1] ])*inv(ξs) - As .|> simplify # returns zero
```

**Comment by mzaffalon** [comment]
It works for me with `SymPy v1.1.7` and `Julia v1.8.5`
```
using SymPy, LinearAlgebra
As=Sym["a" "b"; "c" "d"];
ξs=eigvecs(As);
λs=eigvals(As);
ξs*Diagonal(λs)*inv(ξs) - As .|> simplify # gives a 2x2 zero matrix
```

**Comment by aosidnf** [comment]
I am on the same version of SymPy and Julia.
this zip contains a nix shell and project.toml which produces the issue for me.
https://files.catbox.moe/7vkg5s.zip

**Comment by mzaffalon** [comment]
Can you try a different shell?

**Comment by mzaffalon** [comment]
@jverzani Why sorting? Do `eigvals` and `eigvecs` not have the same ordering?

**Comment by jverzani** [comment]
I’m assuming that the eigenvals are sorted differently in sympy than Julia. If so, perhaps adjusting that would make things more in line.  I’m not sure it would work with symbolic values though.

**Comment by aosidnf** [comment]
i tried other versions of sympy and python (the version in nixos 22.05, and the latest 1.11 in master) and had the same issue. 
It seems ``sympy.ordered()`` will do the job, I'll make a PR later.
