### ISSUE TITLE
Python 3.11 isn't supported, is it?  Where can I check which Python versions each SymPy version supports?

### ISSUE THREAD

**Issue by KierPrev** [JuliaPy/SymPy.jl#500]
Archlinux recently updated to Python 3.11, which doesn't work with SymPy 1.1.8 (the latest). 
Unfortunately, downgrading to 3.10 breaks other stuff...

I'll switch to Kubuntu for the moment.

**Comment by jverzani** [comment]
Let me look to see what can be done. Do you know what doesn't work?

**Comment by KierPrev** [comment]
Executing `using SymPy` with Python 3.11, gives the error
```
caused by: could not load library "/usr/lib/libpython3.10.so.1.0"
/usr/lib/libpython3.10.so.1.0: cannot open shared object file: No such file or directory
```

I guess this version of SymPy only supports up to Python 3.10

**Comment by KierPrev** [comment]
I don't know if this is a SymPy.jl problem, or a PyCall one

**Comment by jverzani** [comment]
Can you try just loading the sympy library with PyCall:

```
julia> using PyCall

julia> sympy = PyCall.pyimport_conda("sympy", "sympy")
PyObject <module 'sympy' from '/Users/verzani/.julia/conda/3/lib/python3.7/site-packages/sympy/__init__.py'>
```

**Comment by KierPrev** [comment]
Thank you, I simply solved it by building again the PyCall  `build PyCall`

**Comment by jverzani** [comment]
Great.  Glad it worked out.
