### ISSUE TITLE
Doc fixes

### ISSUE THREAD

**Issue by jverzani** [JuliaPy/SymPy.jl#504]
The docs here could use some love:
* hosting on gh-pages. 
* some reorganization, landing page is not the tutorial, not should it be...

**Comment by money8203** [comment]
@jverzani I can help with organizing and handling of the docs!

**Comment by jverzani** [comment]
That's great. I was literally just working on some of this. Let me push what I have and then hand the keys over. I haven't set up the hosting through gh-pages yet, so that needs doing along with a general review.

**Comment by jverzani** [comment]
I just pushed #506 once it passes CI, I'll merge in.

**Comment by money8203** [comment]
Awesome, I'll take that

**Comment by jverzani** [comment]
There are a few lines in the `introduction.md` changes that are causing issues with doctests that I didn't see locally. If you want me to adjust, let me know. Otherwise, I'll let you carry on.

**Comment by money8203** [comment]
Sure you can fix that and then I'll start improving the docs

**Comment by jverzani** [comment]
All fixed with #508
