### ISSUE TITLE
[Feature]: Issue Templates

### ISSUE THREAD

**Issue by money8203** [JuliaPy/SymPy.jl#507]
I would like to request the implementation of issue templates for different types of issues in the repository. Having standardized templates will help streamline the issue creation process and ensure that all necessary information is provided for each specific type of issue, like :- 

1. Bug Report Template:

This template will guide users in reporting bugs or unexpected behavior in the project.
> Sections:

- Description of the bug
- Steps to reproduce
- Expected behavior
- Actual behavior
- Environment details (operating system, version, relevant software versions)
- Any additional context or screenshots

2. Feature Request Template:

This template will help users submit feature requests and improvements for the project.
> Sections:

- Description of the requested feature
- Use case behind the request
- Any proposed implementation or alternatives considered
- Additional context or examples

3.Documentation Issue Template:

This template will assist users in reporting issues related to documentation, such as errors, unclear instructions, or missing information.
> Sections:

- Description of the documentation issue
- Location of the issue (specific document, section, or page)
- Suggested improvement or correction
- Any relevant context or examples

**Comment by jverzani** [comment]
Sounds good. I've never set these up before. Is there some guide or could you plumb it in?

**Comment by money8203** [comment]
Yes, there's a whole guide for this https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates

You can go through it if you want else I can hit a pr both for PR and Issue templates

**Comment by jverzani** [comment]
Thanks! This was pretty easy to do.
