### ISSUE TITLE
Matrix multiplication with transpose

### ISSUE THREAD

**Issue by mzaffalon** [JuliaPy/SymPy.jl#512]
In both examples below, I expect the matrix `[p₁]`: 
```
using SymPy

julia> @syms p₁ p₂; B = [1; 0]; P = [p₁ 0; 0 p₂]; transpose(B)*P*B
p₁

julia> B'*P*B
transpose(p₁) # B'*(P*B) -> p₁
```
with SymPy v1.1.9 and Julia v1.9.1.

**Comment by jverzani** [comment]
I just checked and this appears to be inherited from how base Julia handles this product.
