### ISSUE TITLE
SymPy 2.0+ cannot display expressions in an array in the latex form in IJulia 

### ISSUE THREAD

**Issue by waltergu** [JuliaPy/SymPy.jl#543]
Before version 2.0, SymPy supports the display of expressions in an array in the latex form in IJulia, for example, with SymPy@1.2.1
![image](https://github.com/JuliaPy/SymPy.jl/assets/9401967/817f6b01-ad47-441b-9a24-f9ae3cee6fc1)

After update to 2.0+, such pretty display disappears:
![image](https://github.com/JuliaPy/SymPy.jl/assets/9401967/b1e82cec-3ef0-4908-86ed-c30215c0dba6)

**Comment by jverzani** [comment]
Thanks, Let me look to resurrect this feature.
