### ISSUE TITLE
Transfer to JuliaPy?

### ISSUE THREAD

**Issue by stevengj** [JuliaPy/SymPy.jl#87]
cc @ViralBShah

**Comment by ViralBShah** [comment]
@jverzani I already sent you an owner invite to the JuliaPy org.

**Comment by jverzani** [comment]
I'm happy to do this if someone can walk me through the steps.

**Comment by ViralBShah** [comment]
In the settings for your project on github, you will see a transfer button. Then follow the steps.

**Comment by jverzani** [comment]
Thanks, that seemed really easy.

**Comment by stevengj** [comment]
You'll also need to re-enable Travis and AppVeyor.

**Comment by jverzani** [comment]
Any idea how to set up AppVeyor? I don't see a settings tab on this repository once it has been moved to adjust the webhook, assuming that is what needs doing.

**Comment by ViralBShah** [comment]
Cc @tkelman

**Comment by tkelman** [comment]
you have to be an admin in this org to transfer a repo here, so are you sure you aren't seeing a settings tab? https://github.com/JuliaPy/SymPy.jl/settings/hooks/5185295

**Comment by ViralBShah** [comment]
@jverzani is an admin here.
