### ISSUE TITLE
Convert SymPy expression to Julia Expression

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaPy/SymPy.jl#89]
In a macro I computed a matrix of SymPy expressions:

```julia
println(jac)
Any[-y + 1.5 -x; y x - 3]
```

But now I want to bring this back to define a Julia function. Is there a way to do that?

**Comment by ChrisRackauckas** [comment]
I found one way, but is there a way that doesn't require the extra conversions?

```julia
parse(string(jac[1,1]))
```

**Comment by jverzani** [comment]
Try lamdify, I'm guessing that's what you want.

**Comment by ChrisRackauckas** [comment]
Nah, I wanted the AST. Searching though your stuff it looks like parsing it is probably the best option.

**Comment by jverzani** [comment]
Maybe the unexported `walk_expression` does what you want?
