### ISSUE TITLE
SymPy Precompile Issues

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaPy/SymPy.jl#90]
I just created a package which has SymPy as a dependency and it looks like it's having some precompilation issues due to SymPy. You can check the thread here: JuliaDiffEq/ParameterizedFunctions.jl#1

It really boils down to this error:

```julia
using SymPy
INFO: Precompiling module SymPy.
ERROR: LoadError: LoadError: syntax: "(x::Sym,y::Sym)" is not a valid function argument name
 in macro expansion; at ./none:2 [inlined]
 in anonymous at ./<missing>:?
while loading /home/crackauc/.julia/v0.5/SymPy/src/logical.jl, in expression starting on line 5
while loading /home/crackauc/.julia/v0.5/SymPy/src/SymPy.jl, in expression starting on line 123
```

I get this on v0.5-rc4 Linux but not on v0.6 Windows 10. I am also having the same trouble with my CI tests.

**Comment by jverzani** [comment]
Looks like I need to push a change that I made 13 days ago, as master is working for me. I'll do so soon.

**Comment by ChrisRackauckas** [comment]
Updated my SymPy. I changed it to the Conda install because it looks like my SciPy was old. Works.
