### ISSUE TITLE
override show, not display

### ISSUE THREAD

**Issue by stevengj** [JuliaPy/SymPy.jl#92]
For custom pretty-printing of objects, you need to override `show`, not `display`.  See http://docs.julialang.org/en/latest/manual/types/#custom-pretty-printing

(You should *never* override `display` unless you are implementing your own display backend.)

**Comment by stevengj** [comment]
PS. If you know of any other packages that are overriding `display`, please file issues.

**Comment by jmarcellopereira** [comment]
ok, but how to solve? in the juliabox does perfect work

**Comment by stevengj** [comment]
It needs to be solved with a patch to SymPy that overrides `show` rather than `display`.

**Comment by jmarcellopereira** [comment]
but how i do? show command does no works for all expressions
