### ISSUE TITLE
problem  formatting in jupyter with julia 0.5

### ISSUE THREAD

**Issue by jmarcellopereira** [JuliaPy/SymPy.jl#93]
I do not know why, but the formatting in jupyter with julia 0.5 is bad. when I use:

using SymPy
@vars x
x * x

It appears `x ^ 2` instead of `x²`

**Comment by jverzani** [comment]
Thanks for pointing this out

**Comment by jmarcellopereira** [comment]
thanks jverzani, now it's working ;)
