### ISSUE TITLE
Problem polyroots

### ISSUE THREAD

**Issue by jmarcellopereira** [JuliaPy/SymPy.jl#95]
polyroots(x^2 - 4)

UndefVarError: showlimited not defined

 in (::SymPy.#Latex#386)(::Int64) at /home/jmarcellopereira/.julia/v0.5/SymPy/src/display.jl:58
 in show(::IOContext{Base.AbstractIOBuffer{Array{UInt8,1}}}, ::MIME{Symbol("text/latex")}, ::Dict{Any,Any}) at /home/jmarcellopereira/.julia/v0.5/SymPy/src/display.jl:62
 in limitstringmime(::MIME{Symbol("text/latex")}, ::Dict{Any,Any}) at /home/jmarcellopereira/.julia/v0.5/IJulia/src/execute_request.jl:31
 in display_dict(::Dict{Any,Any}) at /home/jmarcellopereira/.julia/v0.5/IJulia/src/execute_request.jl:60
 in execute_request(::ZMQ.Socket, ::IJulia.Msg) at /home/jmarcellopereira/.julia/v0.5/IJulia/src/execute_request.jl:200
 in eventloop(::ZMQ.Socket) at /home/jmarcellopereira/.julia/v0.5/IJulia/src/eventloop.jl:8
 in (::IJulia.##9#15)() at ./task.jl:360

In JuliaBox:
polyroots(x^2 - 4)

{−2 =>1
{ 2 =>1

**Comment by jmarcellopereira** [comment]
is the same mistake with dsolve ()

**Comment by jverzani** [comment]
Thanks again! I'll merge the fix once the tests have passed.

**Comment by jmarcellopereira** [comment]
;)
