### ISSUE TITLE
Display of multidimensional arrays

### ISSUE THREAD

**Issue by molnarandris** [JuliaPy/SymPy.jl#97]
Hi,

I think there is an issue with displaying multi-dimensional arrays:

`MethodError: no method matching (::SymPy.#toeqnarray#383)(::Array{SymPy.Sym,3})`

A possible resolution could be to extend the show function in line 42 of display.jl, e.g. by displaying every 2D slice just like in the case of a usual multi-dimensional array display. 

Thanks for this awesome module.
Andras

**Comment by jverzani** [comment]
Sorry to be so tardy in response. Can you show a little more here? I have:

```
julia> A = zeros(Sym, 2,2,2)
2x2x2 Array{SymPy.Sym,3}:
[:, :, 1] =
 0  0
 0  0

[:, :, 2] =
 0  0
 0  0

julia> convert(SymMatrix,A)
SymPy.SymMatrix(PyObject Matrix([
[[0, 0], [0, 0]],
[[0, 0], [0, 0]]]))
```

So both these display to some degree. But I think you have a different object to display.

**Comment by jverzani** [comment]
Closing, reopen if you want to follow up.
