### ISSUE TITLE
Deprecation warnings -> StackOverflow

### ISSUE THREAD

**Issue by KristofferC** [JuliaPy/SymPy.jl#99]
Running:

```jl
using SymPy
x, L = symbols("x"), symbols("L")
D²(Ψ) = diff(diff(Ψ(x), x), x)
integrate(D²(x -> 1 - x/L)(x), (x, 0, L))
```

gives a stackoverflow error after trying to print an infinite number of deprecation warnings.

**Comment by jverzani** [comment]
Yes, thanks. A bug indeed, as the integrand is 0 and substitution isn't expecting that. Thanks for letting me know.

**Comment by KristofferC** [comment]
Thanks for the quick fix.
